{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Read in Rahul's file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle\n",
    "with open('coord_list.pkl', 'rb') as f:\n",
    "    data = pickle.load(f)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Import a few packages "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from astroquery.simbad import Simbad\n",
    "from astroquery.xmatch import XMatch\n",
    "from astropy import units as u\n",
    "from astropy.table import Table\n",
    "from astropy.coordinates import SkyCoord"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Bring data in my preferred format"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "ra = []\n",
    "dec = []\n",
    "for coord in data:\n",
    "    ra.append(coord.ra.value)\n",
    "    dec.append(coord.dec.value)\n",
    "tab = Table([ra, dec], names=('RA', 'Dec'))\n",
    "tab.write('test.csv', overwrite=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Use the XMatch service"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "xmatch_tab = XMatch.query(cat1=open('test.csv'), \n",
    "                          cat2='SIMBAD', max_distance=0.5* u.arcsec,\n",
    "                          colRA1='RA', colDec1='Dec')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "orig_coord = SkyCoord(ra=tab['RA']*u.degree, dec=tab['Dec']*u.degree)\n",
    "xmatch_coord = SkyCoord(ra=xmatch_tab['RA']*u.degree, dec=xmatch_tab['Dec']*u.degree)\n",
    "idx, d2d, d3d = orig_coord.match_to_catalog_sky(xmatch_coord)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "ind = d2d < 0.5 * u.arcsec"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<SkyCoord (ICRS): (ra, dec) in deg\n",
      "    [(88.69424375,  -6.47762847), (81.57637443,  -6.32723414),\n",
      "     (85.51903637,  -6.40803371), ..., (80.45860846, -16.77345201),\n",
      "     (87.9936909 , -17.75482342), (81.2494604 , -17.44843738)]>\n"
     ]
    }
   ],
   "source": [
    "print(orig_coord[~ind])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Use Simbad directly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "orig_coord = SkyCoord(ra=tab['RA']*u.degree, dec=tab['Dec']*u.degree)\n",
    "search_radius = [2 * u.arcsec] * len(orig_coord)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): '5:54:46.6185 -6:28:39.4625': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 6 raised an error (recorded in the `errors` attribute of the result table): '6:00:43.2001 -6:30:46.0154': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 9 raised an error (recorded in the `errors` attribute of the result table): '5:46:19.8309 -6:25:53.8313': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 12 raised an error (recorded in the `errors` attribute of the result table): '6:03:46.09 -6:31:44.0361': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 15 raised an error (recorded in the `errors` attribute of the result table): '5:44:24.0825 -6:25:19.1065': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 23 raised an error (recorded in the `errors` attribute of the result table): '5:44:42.9476 -6:25:26.0638': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 32 raised an error (recorded in the `errors` attribute of the result table): '6:00:22.2388 -6:33:23.872': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 45 raised an error (recorded in the `errors` attribute of the result table): '5:41:18.6673 -6:30:07.2495': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 55 raised an error (recorded in the `errors` attribute of the result table): '5:41:19.3054 -6:32:59.9194': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 65 raised an error (recorded in the `errors` attribute of the result table): '5:40:55.6155 -6:38:47.3044': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 73 raised an error (recorded in the `errors` attribute of the result table): '5:46:12.6611 -6:42:57.5814': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 87 raised an error (recorded in the `errors` attribute of the result table): '6:07:08.4333 -6:55:03.2392': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 93 raised an error (recorded in the `errors` attribute of the result table): '5:46:03.708 -6:48:18.5233': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 99 raised an error (recorded in the `errors` attribute of the result table): '6:05:47.5077 -6:53:34.6957': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 103 raised an error (recorded in the `errors` attribute of the result table): '6:01:34.973 -6:49:00.8083': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 108 raised an error (recorded in the `errors` attribute of the result table): '6:02:16.9475 -6:51:08.7275': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 119 raised an error (recorded in the `errors` attribute of the result table): '6:04:33.5953 -6:57:14.2722': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 132 raised an error (recorded in the `errors` attribute of the result table): '5:48:22.2628 -6:59:04.8152': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 148 raised an error (recorded in the `errors` attribute of the result table): '5:41:38.0422 -6:51:24.2334': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 157 raised an error (recorded in the `errors` attribute of the result table): '6:04:54.9376 -7:03:12.8796': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 163 raised an error (recorded in the `errors` attribute of the result table): '5:40:01.3065 -6:57:11.7548': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 167 raised an error (recorded in the `errors` attribute of the result table): '6:05:59.5807 -7:01:23.0425': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 174 raised an error (recorded in the `errors` attribute of the result table): '5:32:53.2078 -7:02:59.9611': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 182 raised an error (recorded in the `errors` attribute of the result table): '5:57:49.3457 -6:48:49.8949': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 185 raised an error (recorded in the `errors` attribute of the result table): '5:58:22.1465 -7:03:49.772': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 188 raised an error (recorded in the `errors` attribute of the result table): '5:44:06.7162 -7:09:01.5432': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 198 raised an error (recorded in the `errors` attribute of the result table): '5:43:36.3152 -7:10:07.0705': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 203 raised an error (recorded in the `errors` attribute of the result table): '5:55:29.4151 -6:47:09.457': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 211 raised an error (recorded in the `errors` attribute of the result table): '5:31:23.6858 -7:09:27.3845': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 219 raised an error (recorded in the `errors` attribute of the result table): '6:07:06.7503 -7:25:31.8716': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 235 raised an error (recorded in the `errors` attribute of the result table): '5:50:52.2192 -7:23:19.6157': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 247 raised an error (recorded in the `errors` attribute of the result table): '6:04:34.6992 -7:30:45.2409': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 251 raised an error (recorded in the `errors` attribute of the result table): '5:46:12.1647 -7:19:05.0352': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 255 raised an error (recorded in the `errors` attribute of the result table): '5:45:46.2329 -7:25:43.3861': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 259 raised an error (recorded in the `errors` attribute of the result table): '5:46:18.8278 -7:23:51.1373': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 263 raised an error (recorded in the `errors` attribute of the result table): '6:03:44.3869 -7:33:13.604': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 285 raised an error (recorded in the `errors` attribute of the result table): '5:32:25.9788 -7:26:44.8969': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 288 raised an error (recorded in the `errors` attribute of the result table): '6:02:35.9626 -7:34:35.6695': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 293 raised an error (recorded in the `errors` attribute of the result table): '6:05:05.9639 -7:37:18.2763': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 302 raised an error (recorded in the `errors` attribute of the result table): '5:55:01.914 -7:35:40.9923': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 305 raised an error (recorded in the `errors` attribute of the result table): '5:48:43.0629 -7:28:02.7062': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 313 raised an error (recorded in the `errors` attribute of the result table): '5:31:59.9293 -7:24:25.5454': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 315 raised an error (recorded in the `errors` attribute of the result table): '5:43:54.14 -7:33:27.4551': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 323 raised an error (recorded in the `errors` attribute of the result table): '5:57:55.5832 -7:34:47.8306': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 330 raised an error (recorded in the `errors` attribute of the result table): '5:31:07.7834 -7:31:37.5784': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 338 raised an error (recorded in the `errors` attribute of the result table): '5:47:37.1533 -7:38:13.8004': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 354 raised an error (recorded in the `errors` attribute of the result table): '5:29:23.0097 -7:35:50.4853': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 357 raised an error (recorded in the `errors` attribute of the result table): '5:26:30.6418 -7:34:41.9677': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 360 raised an error (recorded in the `errors` attribute of the result table): '6:05:22.7262 -7:53:05.9215': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 366 raised an error (recorded in the `errors` attribute of the result table): '5:51:03.6421 -7:35:39.4492': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 372 raised an error (recorded in the `errors` attribute of the result table): '6:05:46.2222 -7:49:02.1365': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 374 raised an error (recorded in the `errors` attribute of the result table): '5:45:40.7488 -7:41:08.1906': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 379 raised an error (recorded in the `errors` attribute of the result table): '5:59:59.8441 -7:55:37.6416': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 381 raised an error (recorded in the `errors` attribute of the result table): '5:30:06.6286 -7:18:35.6607': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 385 raised an error (recorded in the `errors` attribute of the result table): '6:04:03.6071 -7:56:43.232': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 392 raised an error (recorded in the `errors` attribute of the result table): '6:00:55.4677 -7:58:45.1929': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 404 raised an error (recorded in the `errors` attribute of the result table): '6:01:48.8443 -8:03:03.8549': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 414 raised an error (recorded in the `errors` attribute of the result table): '5:32:41.7544 -7:51:28.5678': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 420 raised an error (recorded in the `errors` attribute of the result table): '6:03:35.1878 -8:06:02.0825': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 423 raised an error (recorded in the `errors` attribute of the result table): '5:57:49.1351 -8:05:35.21': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 427 raised an error (recorded in the `errors` attribute of the result table): '6:03:44.2203 -8:04:22.2819': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 439 raised an error (recorded in the `errors` attribute of the result table): '5:34:25.5409 -7:59:45.9488': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 444 raised an error (recorded in the `errors` attribute of the result table): '5:37:27.8187 -8:00:49.8493': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 468 raised an error (recorded in the `errors` attribute of the result table): '5:31:31.8753 -8:08:58.1762': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 473 raised an error (recorded in the `errors` attribute of the result table): '5:52:09.7131 -8:15:09.356': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 480 raised an error (recorded in the `errors` attribute of the result table): '5:57:59.4528 -8:21:54.1727': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 493 raised an error (recorded in the `errors` attribute of the result table): '5:58:36.1121 -8:22:53.9066': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 501 raised an error (recorded in the `errors` attribute of the result table): '5:50:17.0742 -8:23:36.5537': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 503 raised an error (recorded in the `errors` attribute of the result table): '5:52:38.6509 -8:09:36.1061': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 510 raised an error (recorded in the `errors` attribute of the result table): '5:51:17.6021 -8:26:18.4644': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 514 raised an error (recorded in the `errors` attribute of the result table): '6:00:49.5903 -8:16:40.0262': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 516 raised an error (recorded in the `errors` attribute of the result table): '6:03:46.8335 -8:32:07.2869': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 518 raised an error (recorded in the `errors` attribute of the result table): '5:24:16.6469 -8:16:16.8974': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 525 raised an error (recorded in the `errors` attribute of the result table): '5:29:18.8373 -8:20:25.1641': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 541 raised an error (recorded in the `errors` attribute of the result table): '5:56:45.0774 -8:39:47.134': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 544 raised an error (recorded in the `errors` attribute of the result table): '5:46:00.3742 -8:31:11.892': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 552 raised an error (recorded in the `errors` attribute of the result table): '6:04:38.9091 -8:44:34.724': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 559 raised an error (recorded in the `errors` attribute of the result table): '5:58:14.336 -8:44:12.0222': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 565 raised an error (recorded in the `errors` attribute of the result table): '6:02:12.9171 -8:41:37.7323': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 572 raised an error (recorded in the `errors` attribute of the result table): '5:52:32.2682 -8:44:59.8645': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 578 raised an error (recorded in the `errors` attribute of the result table): '5:27:52.0167 -8:33:54.9608': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 583 raised an error (recorded in the `errors` attribute of the result table): '5:47:49.7984 -8:40:59.2733': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 593 raised an error (recorded in the `errors` attribute of the result table): '5:28:13.8045 -8:37:52.8216': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 597 raised an error (recorded in the `errors` attribute of the result table): '5:28:03.674 -8:40:18.5428': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 605 raised an error (recorded in the `errors` attribute of the result table): '5:51:25.6588 -8:52:09.0567': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 610 raised an error (recorded in the `errors` attribute of the result table): '5:35:05.9998 -8:44:08.4317': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 618 raised an error (recorded in the `errors` attribute of the result table): '5:56:04.9929 -8:56:43.1457': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 623 raised an error (recorded in the `errors` attribute of the result table): '5:22:51.2162 -8:43:41.965': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 631 raised an error (recorded in the `errors` attribute of the result table): '6:06:40.7675 -9:06:07.4004': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 637 raised an error (recorded in the `errors` attribute of the result table): '5:24:00.0726 -8:39:55.811': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 650 raised an error (recorded in the `errors` attribute of the result table): '6:06:58.3749 -9:07:22.1416': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 658 raised an error (recorded in the `errors` attribute of the result table): '5:24:25.0088 -8:45:42.9524': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 663 raised an error (recorded in the `errors` attribute of the result table): '5:37:52.2177 -8:58:03.4065': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 673 raised an error (recorded in the `errors` attribute of the result table): '6:01:29.2563 -9:07:25.5798': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 685 raised an error (recorded in the `errors` attribute of the result table): '5:47:10.2104 -9:08:27.3413': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 688 raised an error (recorded in the `errors` attribute of the result table): '5:34:53.3733 -9:02:48.5651': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 694 raised an error (recorded in the `errors` attribute of the result table): '6:01:21.434 -9:10:03.1232': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 698 raised an error (recorded in the `errors` attribute of the result table): '5:37:11.3435 -9:06:55.1523': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 703 raised an error (recorded in the `errors` attribute of the result table): '5:53:41.9848 -9:17:42.4057': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 708 raised an error (recorded in the `errors` attribute of the result table): '5:30:28.5884 -9:05:02.4385': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 711 raised an error (recorded in the `errors` attribute of the result table): '5:36:30.5052 -9:05:32.3889': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 715 raised an error (recorded in the `errors` attribute of the result table): '5:52:57.9198 -9:16:37.3207': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 730 raised an error (recorded in the `errors` attribute of the result table): '6:02:52.8541 -9:28:46.9649': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 738 raised an error (recorded in the `errors` attribute of the result table): '5:50:01.8876 -9:23:27.6186': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 740 raised an error (recorded in the `errors` attribute of the result table): '5:51:19.5216 -9:26:09.6465': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 742 raised an error (recorded in the `errors` attribute of the result table): '5:38:05.674 -9:16:21.2629': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 752 raised an error (recorded in the `errors` attribute of the result table): '5:35:56.0098 -9:21:13.2321': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 755 raised an error (recorded in the `errors` attribute of the result table): '6:00:45.8942 -9:33:34.1958': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 761 raised an error (recorded in the `errors` attribute of the result table): '5:25:06.4178 -9:13:18.2471': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 766 raised an error (recorded in the `errors` attribute of the result table): '5:25:16.9126 -9:13:53.512': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 770 raised an error (recorded in the `errors` attribute of the result table): '5:28:11.8192 -9:19:28.0712': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 779 raised an error (recorded in the `errors` attribute of the result table): '5:47:49.0469 -9:29:13.6592': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 781 raised an error (recorded in the `errors` attribute of the result table): '5:38:25.0442 -9:14:39.5031': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 791 raised an error (recorded in the `errors` attribute of the result table): '5:56:01.7025 -9:39:10.0786': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 794 raised an error (recorded in the `errors` attribute of the result table): '5:47:48.1706 -9:27:28.6333': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 799 raised an error (recorded in the `errors` attribute of the result table): '5:55:46.0747 -9:43:46.8366': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 802 raised an error (recorded in the `errors` attribute of the result table): '5:56:36.4287 -9:40:20.4618': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 806 raised an error (recorded in the `errors` attribute of the result table): '5:28:44.7065 -9:29:56.3946': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 814 raised an error (recorded in the `errors` attribute of the result table): '5:37:34.9921 -9:34:08.0259': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 820 raised an error (recorded in the `errors` attribute of the result table): '5:43:53.3434 -9:28:28.5713': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 825 raised an error (recorded in the `errors` attribute of the result table): '5:54:02.6077 -9:46:49.4173': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 828 raised an error (recorded in the `errors` attribute of the result table): '6:07:30.6358 -9:46:58.9726': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 834 raised an error (recorded in the `errors` attribute of the result table): '6:01:49.6607 -9:46:23.9903': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 838 raised an error (recorded in the `errors` attribute of the result table): '5:59:01.1278 -9:44:10.3107': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 842 raised an error (recorded in the `errors` attribute of the result table): '6:05:36.5501 -9:44:30.4541': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 847 raised an error (recorded in the `errors` attribute of the result table): '5:26:55.9108 -9:34:06.6331': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 854 raised an error (recorded in the `errors` attribute of the result table): '5:34:59.2385 -9:40:07.9531': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 857 raised an error (recorded in the `errors` attribute of the result table): '5:54:01.957 -9:51:06.8988': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 874 raised an error (recorded in the `errors` attribute of the result table): '5:45:33.5441 -9:52:24.072': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 881 raised an error (recorded in the `errors` attribute of the result table): '5:46:06.6171 -9:54:01.9199': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 887 raised an error (recorded in the `errors` attribute of the result table): '5:51:37.8837 -9:50:51.1859': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 895 raised an error (recorded in the `errors` attribute of the result table): '5:21:25.7167 -9:46:28.0244': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 900 raised an error (recorded in the `errors` attribute of the result table): '5:49:59.6803 -9:54:19.362': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 906 raised an error (recorded in the `errors` attribute of the result table): '5:49:55.1768 -9:59:12.0007': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 913 raised an error (recorded in the `errors` attribute of the result table): '6:06:10.6453 -10:06:27.1448': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 920 raised an error (recorded in the `errors` attribute of the result table): '5:21:29.3633 -9:39:37.3439': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 928 raised an error (recorded in the `errors` attribute of the result table): '5:40:26.4392 -10:00:29.6073': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 935 raised an error (recorded in the `errors` attribute of the result table): '5:48:20.9278 -10:05:54.7594': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 939 raised an error (recorded in the `errors` attribute of the result table): '6:03:27.472 -10:09:49.2621': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 944 raised an error (recorded in the `errors` attribute of the result table): '5:34:09.6733 -9:59:34.7145': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 957 raised an error (recorded in the `errors` attribute of the result table): '6:00:38.8029 -10:16:32.2714': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 961 raised an error (recorded in the `errors` attribute of the result table): '6:01:37.7956 -10:09:19.2177': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 965 raised an error (recorded in the `errors` attribute of the result table): '5:58:50.108 -10:10:01.1538': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 968 raised an error (recorded in the `errors` attribute of the result table): '5:51:56.7625 -10:09:29.783': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 971 raised an error (recorded in the `errors` attribute of the result table): '5:43:54.3848 -10:11:04.5784': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 981 raised an error (recorded in the `errors` attribute of the result table): '5:37:19.7584 -10:07:38.6717': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 986 raised an error (recorded in the `errors` attribute of the result table): '5:44:51.1542 -10:14:20.5122': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 990 raised an error (recorded in the `errors` attribute of the result table): '5:58:56.6341 -10:16:18.4375': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 994 raised an error (recorded in the `errors` attribute of the result table): '5:59:41.5971 -10:21:02.7389': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 996 raised an error (recorded in the `errors` attribute of the result table): '5:35:48.9947 -10:11:09.0201': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 998 raised an error (recorded in the `errors` attribute of the result table): '5:57:46.369 -10:17:26.3461': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1003 raised an error (recorded in the `errors` attribute of the result table): '6:02:44.5017 -10:16:04.5383': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1013 raised an error (recorded in the `errors` attribute of the result table): '5:31:31.9378 -10:09:13.4706': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1020 raised an error (recorded in the `errors` attribute of the result table): '6:03:30.5401 -10:26:40.8129': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1023 raised an error (recorded in the `errors` attribute of the result table): '5:42:00.0561 -10:18:39.7155': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1027 raised an error (recorded in the `errors` attribute of the result table): '5:44:13.9341 -10:20:24.9753': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1029 raised an error (recorded in the `errors` attribute of the result table): '6:00:51.3898 -10:28:15.037': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1034 raised an error (recorded in the `errors` attribute of the result table): '6:05:00.9803 -10:28:17.0472': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1038 raised an error (recorded in the `errors` attribute of the result table): '6:06:12.1692 -10:28:49.6203': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1042 raised an error (recorded in the `errors` attribute of the result table): '5:25:45.4878 -10:07:25.5397': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1046 raised an error (recorded in the `errors` attribute of the result table): '5:29:38.5767 -10:15:16.9531': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1049 raised an error (recorded in the `errors` attribute of the result table): '5:59:54.5383 -10:28:50.5337': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1052 raised an error (recorded in the `errors` attribute of the result table): '5:28:29.5906 -10:15:57.0752': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1054 raised an error (recorded in the `errors` attribute of the result table): '5:31:00.0281 -10:15:42.0941': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1057 raised an error (recorded in the `errors` attribute of the result table): '6:05:25.9091 -10:34:02.7258': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1064 raised an error (recorded in the `errors` attribute of the result table): '5:30:04.0167 -10:21:26.8709': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1071 raised an error (recorded in the `errors` attribute of the result table): '5:49:47.3832 -10:34:41.4704': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1075 raised an error (recorded in the `errors` attribute of the result table): '5:50:23.8947 -10:35:29.5459': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1079 raised an error (recorded in the `errors` attribute of the result table): '5:56:40.1311 -10:32:52.7114': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1084 raised an error (recorded in the `errors` attribute of the result table): '5:37:06.3276 -10:32:05.566': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1086 raised an error (recorded in the `errors` attribute of the result table): '6:07:15.4342 -10:41:01.1': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1090 raised an error (recorded in the `errors` attribute of the result table): '5:56:51.2754 -10:39:34.8636': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1093 raised an error (recorded in the `errors` attribute of the result table): '5:38:37.8236 -10:34:35.9214': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1096 raised an error (recorded in the `errors` attribute of the result table): '6:04:28.8998 -10:49:16.9583': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1099 raised an error (recorded in the `errors` attribute of the result table): '5:22:02.6074 -10:20:33.5777': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1108 raised an error (recorded in the `errors` attribute of the result table): '5:56:17.4881 -10:51:48.1564': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1112 raised an error (recorded in the `errors` attribute of the result table): '5:47:57.945 -10:45:25.9642': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1114 raised an error (recorded in the `errors` attribute of the result table): '5:47:42.8781 -9:51:59.13': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1118 raised an error (recorded in the `errors` attribute of the result table): '6:03:02.0754 -10:50:54.4284': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1126 raised an error (recorded in the `errors` attribute of the result table): '5:40:46.541 -10:40:25.474': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1130 raised an error (recorded in the `errors` attribute of the result table): '5:48:33.9123 -10:50:21.1677': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1134 raised an error (recorded in the `errors` attribute of the result table): '5:59:26.9922 -10:49:00.1195': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1136 raised an error (recorded in the `errors` attribute of the result table): '5:44:03.3229 -10:48:23.797': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1140 raised an error (recorded in the `errors` attribute of the result table): '5:33:12.4262 -10:40:44.0184': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1144 raised an error (recorded in the `errors` attribute of the result table): '5:59:22.5182 -10:56:16.7286': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1146 raised an error (recorded in the `errors` attribute of the result table): '5:55:55.5649 -10:58:50.0298': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1154 raised an error (recorded in the `errors` attribute of the result table): '5:32:48.9869 -10:45:27.9926': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1158 raised an error (recorded in the `errors` attribute of the result table): '5:59:04.3899 -11:00:51.3037': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1163 raised an error (recorded in the `errors` attribute of the result table): '5:46:09.0737 -10:56:22.3786': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1166 raised an error (recorded in the `errors` attribute of the result table): '5:29:16.7607 -10:49:40.0347': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1171 raised an error (recorded in the `errors` attribute of the result table): '5:22:17.5528 -10:42:26.3406': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1178 raised an error (recorded in the `errors` attribute of the result table): '5:52:20.3642 -11:04:11.2447': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1185 raised an error (recorded in the `errors` attribute of the result table): '5:59:41.3803 -11:09:07.6472': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1193 raised an error (recorded in the `errors` attribute of the result table): '5:52:15.8362 -11:10:45.6122': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1196 raised an error (recorded in the `errors` attribute of the result table): '5:38:02.0124 -11:02:34.989': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1205 raised an error (recorded in the `errors` attribute of the result table): '5:47:51.1853 -11:09:16.3636': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1212 raised an error (recorded in the `errors` attribute of the result table): '6:04:51.9567 -11:15:26.6939': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1217 raised an error (recorded in the `errors` attribute of the result table): '5:42:00.5259 -11:04:10.9192': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1219 raised an error (recorded in the `errors` attribute of the result table): '5:51:54.0234 -11:08:20.9936': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1224 raised an error (recorded in the `errors` attribute of the result table): '5:51:33.0225 -11:13:47.6596': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1234 raised an error (recorded in the `errors` attribute of the result table): '5:44:18.0902 -11:11:52.2686': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1236 raised an error (recorded in the `errors` attribute of the result table): '5:50:53.8174 -11:12:06.6459': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1240 raised an error (recorded in the `errors` attribute of the result table): '5:27:38.6057 -11:02:58.7372': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1246 raised an error (recorded in the `errors` attribute of the result table): '5:53:03.3144 -11:14:17.5927': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1256 raised an error (recorded in the `errors` attribute of the result table): '5:42:34.6258 -11:13:53.5921': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1262 raised an error (recorded in the `errors` attribute of the result table): '5:47:09.5771 -11:17:51.4356': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1273 raised an error (recorded in the `errors` attribute of the result table): '5:59:32.5649 -11:25:24.7682': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1283 raised an error (recorded in the `errors` attribute of the result table): '6:01:31.2192 -11:24:59.5484': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1290 raised an error (recorded in the `errors` attribute of the result table): '5:58:52.3918 -11:28:43.4164': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1292 raised an error (recorded in the `errors` attribute of the result table): '5:48:50.0253 -11:25:19.541': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1295 raised an error (recorded in the `errors` attribute of the result table): '6:03:53.249 -11:32:26.8872': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1299 raised an error (recorded in the `errors` attribute of the result table): '5:50:51.6315 -11:31:12.243': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1301 raised an error (recorded in the `errors` attribute of the result table): '5:51:32.4461 -11:31:22.3709': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1306 raised an error (recorded in the `errors` attribute of the result table): '5:36:09.4889 -11:22:34.7733': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1313 raised an error (recorded in the `errors` attribute of the result table): '6:00:34.9636 -11:36:11.4814': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1322 raised an error (recorded in the `errors` attribute of the result table): '5:35:09.9859 -11:27:40.9748': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1324 raised an error (recorded in the `errors` attribute of the result table): '6:06:37.9402 -11:37:53.1302': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1327 raised an error (recorded in the `errors` attribute of the result table): '5:52:38.494 -11:37:35.7506': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1332 raised an error (recorded in the `errors` attribute of the result table): '5:33:12.4284 -11:27:53.845': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1337 raised an error (recorded in the `errors` attribute of the result table): '5:47:41.9406 -11:38:37.0505': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1341 raised an error (recorded in the `errors` attribute of the result table): '6:06:15.7665 -11:45:38.8334': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1351 raised an error (recorded in the `errors` attribute of the result table): '5:52:21.2707 -11:45:44.0349': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1353 raised an error (recorded in the `errors` attribute of the result table): '5:28:46.1873 -11:29:17.8951': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1356 raised an error (recorded in the `errors` attribute of the result table): '5:22:47.6726 -11:26:22.1294': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1364 raised an error (recorded in the `errors` attribute of the result table): '5:48:43.9957 -11:44:17.2307': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1369 raised an error (recorded in the `errors` attribute of the result table): '6:03:38.883 -11:50:43.5386': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1376 raised an error (recorded in the `errors` attribute of the result table): '5:45:41.4029 -11:48:37.2885': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1380 raised an error (recorded in the `errors` attribute of the result table): '6:02:58.7719 -11:57:06.2149': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1392 raised an error (recorded in the `errors` attribute of the result table): '5:27:53.6734 -11:38:23.7659': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1395 raised an error (recorded in the `errors` attribute of the result table): '5:27:23.3285 -11:45:39.9877': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1410 raised an error (recorded in the `errors` attribute of the result table): '6:04:35.8842 -12:07:50.0944': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1419 raised an error (recorded in the `errors` attribute of the result table): '6:06:16.3712 -12:11:44.211': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1422 raised an error (recorded in the `errors` attribute of the result table): '5:43:21.765 -12:02:22.3493': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1428 raised an error (recorded in the `errors` attribute of the result table): '5:54:03.1242 -12:07:47.8057': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1431 raised an error (recorded in the `errors` attribute of the result table): '5:40:49.2083 -12:07:34.3844': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1443 raised an error (recorded in the `errors` attribute of the result table): '5:30:02.5868 -12:01:58.1857': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1449 raised an error (recorded in the `errors` attribute of the result table): '5:57:57.4875 -11:32:37.8814': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1456 raised an error (recorded in the `errors` attribute of the result table): '5:55:57.4582 -12:02:19.7481': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1462 raised an error (recorded in the `errors` attribute of the result table): '5:53:31.543 -12:19:26.4582': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1465 raised an error (recorded in the `errors` attribute of the result table): '5:40:35.2588 -12:09:59.9842': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1468 raised an error (recorded in the `errors` attribute of the result table): '5:47:57.4543 -12:14:34.9119': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1471 raised an error (recorded in the `errors` attribute of the result table): '5:37:17.5627 -12:09:36.0082': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1489 raised an error (recorded in the `errors` attribute of the result table): '6:01:21.4196 -12:24:07.9932': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1500 raised an error (recorded in the `errors` attribute of the result table): '5:49:05.4114 -12:13:58.944': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1511 raised an error (recorded in the `errors` attribute of the result table): '5:59:27.0082 -12:30:46.6908': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1515 raised an error (recorded in the `errors` attribute of the result table): '5:59:01.0555 -12:31:45.5122': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1523 raised an error (recorded in the `errors` attribute of the result table): '5:31:17.363 -11:59:12.5083': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1525 raised an error (recorded in the `errors` attribute of the result table): '5:32:55.8142 -12:04:22.3345': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1528 raised an error (recorded in the `errors` attribute of the result table): '5:31:09.7831 -11:43:07.4501': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1530 raised an error (recorded in the `errors` attribute of the result table): '6:02:33.8842 -12:38:05.0404': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1538 raised an error (recorded in the `errors` attribute of the result table): '6:03:40.2701 -12:30:09.0346': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1543 raised an error (recorded in the `errors` attribute of the result table): '6:05:50.4235 -12:40:00.5496': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1546 raised an error (recorded in the `errors` attribute of the result table): '5:39:00.3296 -12:28:53.1322': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1549 raised an error (recorded in the `errors` attribute of the result table): '5:39:17.6251 -12:29:57.5544': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1572 raised an error (recorded in the `errors` attribute of the result table): '6:05:42.7854 -12:49:58.3297': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1575 raised an error (recorded in the `errors` attribute of the result table): '5:46:48.6357 -12:39:30.8201': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1578 raised an error (recorded in the `errors` attribute of the result table): '5:39:13.6299 -12:34:03.3789': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1584 raised an error (recorded in the `errors` attribute of the result table): '5:33:01.0867 -12:27:37.637': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1586 raised an error (recorded in the `errors` attribute of the result table): '6:04:36.1835 -12:49:08.5253': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1592 raised an error (recorded in the `errors` attribute of the result table): '5:52:49.0231 -12:37:36.3185': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1600 raised an error (recorded in the `errors` attribute of the result table): '5:58:14.9856 -12:50:49.4119': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1608 raised an error (recorded in the `errors` attribute of the result table): '5:58:36.8336 -12:50:22.2686': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1612 raised an error (recorded in the `errors` attribute of the result table): '5:35:02.9375 -12:40:10.4208': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1616 raised an error (recorded in the `errors` attribute of the result table): '6:04:36.6336 -12:54:49.7645': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1626 raised an error (recorded in the `errors` attribute of the result table): '5:48:51.1957 -12:51:30.6717': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1631 raised an error (recorded in the `errors` attribute of the result table): '5:32:51.716 -12:41:33.0182': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1636 raised an error (recorded in the `errors` attribute of the result table): '5:35:53.5204 -12:45:32.6241': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1645 raised an error (recorded in the `errors` attribute of the result table): '5:58:42.0951 -13:00:21.9401': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1653 raised an error (recorded in the `errors` attribute of the result table): '5:57:31.8168 -12:50:52.1723': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1667 raised an error (recorded in the `errors` attribute of the result table): '6:02:37.3164 -13:05:32.6312': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1673 raised an error (recorded in the `errors` attribute of the result table): '6:04:02.7171 -13:06:56.2124': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1688 raised an error (recorded in the `errors` attribute of the result table): '5:52:57.8397 -13:05:11.78': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1693 raised an error (recorded in the `errors` attribute of the result table): '5:39:46.0911 -12:50:13.8973': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1701 raised an error (recorded in the `errors` attribute of the result table): '6:02:34.8316 -13:13:58.7512': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1709 raised an error (recorded in the `errors` attribute of the result table): '5:58:21.2142 -13:12:25.4209': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1713 raised an error (recorded in the `errors` attribute of the result table): '5:30:02.8094 -12:53:37.9872': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1716 raised an error (recorded in the `errors` attribute of the result table): '5:51:16.3404 -12:53:42.2305': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1721 raised an error (recorded in the `errors` attribute of the result table): '5:53:40.9211 -13:08:01.9616': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1734 raised an error (recorded in the `errors` attribute of the result table): '6:01:17.0248 -13:20:55.7979': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1741 raised an error (recorded in the `errors` attribute of the result table): '5:58:57.0913 -13:23:26.382': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1744 raised an error (recorded in the `errors` attribute of the result table): '5:45:09.1751 -13:09:37.7403': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1750 raised an error (recorded in the `errors` attribute of the result table): '5:28:24.1953 -13:03:46.9855': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1758 raised an error (recorded in the `errors` attribute of the result table): '5:51:16.2338 -13:15:15.8514': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1764 raised an error (recorded in the `errors` attribute of the result table): '6:00:27.4447 -13:21:23.7478': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1769 raised an error (recorded in the `errors` attribute of the result table): '5:36:45.1219 -13:10:30.2938': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1772 raised an error (recorded in the `errors` attribute of the result table): '5:59:31.3189 -13:24:06.1087': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1786 raised an error (recorded in the `errors` attribute of the result table): '5:23:15.6793 -13:00:50.1795': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1792 raised an error (recorded in the `errors` attribute of the result table): '5:59:36.587 -13:30:09.5998': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1795 raised an error (recorded in the `errors` attribute of the result table): '6:02:43.5033 -13:30:41.4178': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1814 raised an error (recorded in the `errors` attribute of the result table): '6:02:48.8209 -13:34:38.9007': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1821 raised an error (recorded in the `errors` attribute of the result table): '5:58:36.2481 -13:36:20.0423': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1824 raised an error (recorded in the `errors` attribute of the result table): '5:43:12.8233 -13:26:31.6856': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1833 raised an error (recorded in the `errors` attribute of the result table): '5:58:13.4941 -13:35:47.009': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1842 raised an error (recorded in the `errors` attribute of the result table): '5:56:28.2821 -13:37:36.8131': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1845 raised an error (recorded in the `errors` attribute of the result table): '5:47:12.4814 -13:33:53.0635': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1849 raised an error (recorded in the `errors` attribute of the result table): '5:58:20.6227 -13:41:13.8309': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1867 raised an error (recorded in the `errors` attribute of the result table): '5:23:11.8668 -13:16:04.1944': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1875 raised an error (recorded in the `errors` attribute of the result table): '5:42:26.9469 -13:38:16.5155': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1881 raised an error (recorded in the `errors` attribute of the result table): '6:01:20.83 -13:49:25.3813': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1885 raised an error (recorded in the `errors` attribute of the result table): '5:47:59.4964 -13:46:27.2773': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1898 raised an error (recorded in the `errors` attribute of the result table): '5:44:12.4705 -13:46:17.7879': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1905 raised an error (recorded in the `errors` attribute of the result table): '5:45:27.8472 -13:49:44.0118': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1909 raised an error (recorded in the `errors` attribute of the result table): '5:47:23.2219 -13:50:58.2834': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1915 raised an error (recorded in the `errors` attribute of the result table): '6:02:04.6232 -13:57:54.9045': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1924 raised an error (recorded in the `errors` attribute of the result table): '5:56:53.0574 -13:56:34.744': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1930 raised an error (recorded in the `errors` attribute of the result table): '5:57:04.3657 -13:57:52.1817': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1933 raised an error (recorded in the `errors` attribute of the result table): '5:35:02.2356 -13:45:13.8418': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1939 raised an error (recorded in the `errors` attribute of the result table): '5:58:25.7683 -14:02:59.8977': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1941 raised an error (recorded in the `errors` attribute of the result table): '5:41:26.4503 -13:53:34.5302': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1945 raised an error (recorded in the `errors` attribute of the result table): '6:06:43.2875 -14:07:30.0118': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1951 raised an error (recorded in the `errors` attribute of the result table): '5:45:00.9076 -13:58:39.2815': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1955 raised an error (recorded in the `errors` attribute of the result table): '5:41:29.2576 -13:59:02.6253': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1975 raised an error (recorded in the `errors` attribute of the result table): '5:30:18.821 -13:36:13.1743': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1981 raised an error (recorded in the `errors` attribute of the result table): '6:03:44.8783 -14:16:55.9713': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 1995 raised an error (recorded in the `errors` attribute of the result table): '5:37:21.5933 -14:02:00.6773': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2000 raised an error (recorded in the `errors` attribute of the result table): '5:36:33.3088 -14:04:01.3337': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2019 raised an error (recorded in the `errors` attribute of the result table): '5:58:49.5866 -14:26:56.0054': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2023 raised an error (recorded in the `errors` attribute of the result table): '6:00:13.5919 -14:25:44.7791': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2031 raised an error (recorded in the `errors` attribute of the result table): '6:04:40.0181 -14:31:36.9435': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2037 raised an error (recorded in the `errors` attribute of the result table): '6:05:04.8303 -14:33:51.1723': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2040 raised an error (recorded in the `errors` attribute of the result table): '5:38:30.146 -13:51:27.3176': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2052 raised an error (recorded in the `errors` attribute of the result table): '5:36:55.6527 -14:17:36.1402': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2055 raised an error (recorded in the `errors` attribute of the result table): '5:40:54.2649 -14:22:52.0318': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2074 raised an error (recorded in the `errors` attribute of the result table): '5:38:26.4287 -14:23:43.3761': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2076 raised an error (recorded in the `errors` attribute of the result table): '5:36:19.9487 -14:22:51.4259': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2083 raised an error (recorded in the `errors` attribute of the result table): '5:49:17.9338 -14:33:44.4131': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2088 raised an error (recorded in the `errors` attribute of the result table): '5:47:54.7627 -14:31:06.3449': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2094 raised an error (recorded in the `errors` attribute of the result table): '5:42:43.917 -14:32:30.8836': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2109 raised an error (recorded in the `errors` attribute of the result table): '5:59:01.367 -14:40:07.0515': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2120 raised an error (recorded in the `errors` attribute of the result table): '6:01:24.2032 -14:48:41.9362': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2127 raised an error (recorded in the `errors` attribute of the result table): '5:29:04.0816 -14:25:15.4746': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2132 raised an error (recorded in the `errors` attribute of the result table): '5:57:40.5452 -14:44:23.3547': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2149 raised an error (recorded in the `errors` attribute of the result table): '5:48:06.7942 -14:41:47.8065': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2161 raised an error (recorded in the `errors` attribute of the result table): '5:56:23.035 -14:15:50.4645': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2166 raised an error (recorded in the `errors` attribute of the result table): '5:41:46.7664 -14:41:46.7697': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2173 raised an error (recorded in the `errors` attribute of the result table): '5:29:42.1011 -14:34:29.9318': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2176 raised an error (recorded in the `errors` attribute of the result table): '6:04:34.4377 -14:57:05.6067': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2180 raised an error (recorded in the `errors` attribute of the result table): '6:03:02.1951 -14:49:31.4183': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2182 raised an error (recorded in the `errors` attribute of the result table): '5:58:25.6806 -14:58:06.8966': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2184 raised an error (recorded in the `errors` attribute of the result table): '6:02:31.7438 -15:00:26.7823': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2193 raised an error (recorded in the `errors` attribute of the result table): '5:57:44.9941 -14:58:43.0376': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2208 raised an error (recorded in the `errors` attribute of the result table): '6:02:08.3227 -15:04:51.0852': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2213 raised an error (recorded in the `errors` attribute of the result table): '6:03:05.4659 -15:01:41.6537': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2217 raised an error (recorded in the `errors` attribute of the result table): '5:22:20.2934 -14:39:04.8036': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2220 raised an error (recorded in the `errors` attribute of the result table): '6:00:20.6131 -15:05:04.0601': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2226 raised an error (recorded in the `errors` attribute of the result table): '6:03:53.9469 -15:09:26.3616': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2237 raised an error (recorded in the `errors` attribute of the result table): '6:05:42.1237 -15:09:04.5894': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2245 raised an error (recorded in the `errors` attribute of the result table): '5:56:16.7955 -15:10:43.9969': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2247 raised an error (recorded in the `errors` attribute of the result table): '5:46:02.4626 -15:04:06.3952': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2256 raised an error (recorded in the `errors` attribute of the result table): '6:05:16.7151 -15:17:20.1164': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2262 raised an error (recorded in the `errors` attribute of the result table): '5:34:38.9309 -15:01:06.2779': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2274 raised an error (recorded in the `errors` attribute of the result table): '5:28:56.6478 -15:01:32.4247': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2280 raised an error (recorded in the `errors` attribute of the result table): '6:01:46.2571 -15:23:55.4338': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2287 raised an error (recorded in the `errors` attribute of the result table): '5:28:15.9678 -15:03:44.1601': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2292 raised an error (recorded in the `errors` attribute of the result table): '5:38:14.9966 -15:12:32.6846': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2301 raised an error (recorded in the `errors` attribute of the result table): '5:38:54.4224 -15:17:27.6762': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2313 raised an error (recorded in the `errors` attribute of the result table): '5:25:37.6902 -15:05:22.4564': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2315 raised an error (recorded in the `errors` attribute of the result table): '5:51:00.541 -15:25:51.1774': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2318 raised an error (recorded in the `errors` attribute of the result table): '6:02:44.6112 -15:32:52.4318': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2339 raised an error (recorded in the `errors` attribute of the result table): '5:54:54.131 -15:37:41.2091': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2352 raised an error (recorded in the `errors` attribute of the result table): '6:01:59.07 -15:45:37.4305': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2365 raised an error (recorded in the `errors` attribute of the result table): '5:44:22.8052 -15:37:08.0625': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2384 raised an error (recorded in the `errors` attribute of the result table): '5:44:38.91 -15:42:16.9409': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2398 raised an error (recorded in the `errors` attribute of the result table): '6:02:15.8586 -15:50:31.3659': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2402 raised an error (recorded in the `errors` attribute of the result table): '6:02:34.8517 -15:55:15.3838': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2407 raised an error (recorded in the `errors` attribute of the result table): '5:58:22.6937 -15:47:57.7828': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2413 raised an error (recorded in the `errors` attribute of the result table): '5:38:30.8756 -15:41:11.569': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2421 raised an error (recorded in the `errors` attribute of the result table): '5:53:15.1843 -15:54:16.9806': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2425 raised an error (recorded in the `errors` attribute of the result table): '5:44:42.7273 -15:49:45.9831': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2432 raised an error (recorded in the `errors` attribute of the result table): '6:01:20.9786 -15:46:53.8296': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2438 raised an error (recorded in the `errors` attribute of the result table): '5:38:59.6123 -15:40:53.385': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2450 raised an error (recorded in the `errors` attribute of the result table): '6:02:53.4048 -15:58:28.6456': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2453 raised an error (recorded in the `errors` attribute of the result table): '5:50:44.5101 -15:55:12.3485': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2465 raised an error (recorded in the `errors` attribute of the result table): '6:01:43.639 -16:08:17.4989': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2471 raised an error (recorded in the `errors` attribute of the result table): '5:27:49.5091 -15:43:10.7256': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2474 raised an error (recorded in the `errors` attribute of the result table): '5:27:07.502 -15:39:31.5702': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2491 raised an error (recorded in the `errors` attribute of the result table): '5:21:10.8081 -15:38:40.5108': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2500 raised an error (recorded in the `errors` attribute of the result table): '5:45:22.7356 -16:05:20.518': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2510 raised an error (recorded in the `errors` attribute of the result table): '5:48:49.6892 -15:53:15.7208': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2524 raised an error (recorded in the `errors` attribute of the result table): '5:55:16.3293 -16:14:50.7978': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2528 raised an error (recorded in the `errors` attribute of the result table): '5:43:55.9988 -16:09:54.0997': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2535 raised an error (recorded in the `errors` attribute of the result table): '6:02:05.7237 -16:16:14.7083': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2545 raised an error (recorded in the `errors` attribute of the result table): '6:04:37.4711 -16:19:13.2679': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2550 raised an error (recorded in the `errors` attribute of the result table): '6:01:58.447 -16:22:22.9964': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2558 raised an error (recorded in the `errors` attribute of the result table): '5:34:47.8916 -16:02:39.1908': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2566 raised an error (recorded in the `errors` attribute of the result table): '6:03:47.8026 -16:18:49.0863': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2568 raised an error (recorded in the `errors` attribute of the result table): '5:40:21.0398 -16:11:14.2048': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2576 raised an error (recorded in the `errors` attribute of the result table): '5:56:16.1626 -16:20:16.3474': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2579 raised an error (recorded in the `errors` attribute of the result table): '5:52:48.2593 -16:13:20.2533': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2583 raised an error (recorded in the `errors` attribute of the result table): '5:52:02.0975 -16:21:33.4352': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2586 raised an error (recorded in the `errors` attribute of the result table): '5:51:48.4925 -16:23:33.3662': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2590 raised an error (recorded in the `errors` attribute of the result table): '5:54:48.9671 -16:25:17.377': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2607 raised an error (recorded in the `errors` attribute of the result table): '6:03:36.2319 -16:32:45.0899': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2611 raised an error (recorded in the `errors` attribute of the result table): '5:34:46.997 -16:14:43.2781': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2620 raised an error (recorded in the `errors` attribute of the result table): '5:27:30.8109 -16:12:29.8551': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2630 raised an error (recorded in the `errors` attribute of the result table): '5:50:33.6703 -16:23:23.7406': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2634 raised an error (recorded in the `errors` attribute of the result table): '5:45:58.7901 -16:28:22.4686': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2641 raised an error (recorded in the `errors` attribute of the result table): '5:20:25.0435 -16:11:38.7575': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2643 raised an error (recorded in the `errors` attribute of the result table): '5:57:07.2718 -16:41:53.4466': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2646 raised an error (recorded in the `errors` attribute of the result table): '6:02:56.0863 -16:39:46.5148': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2654 raised an error (recorded in the `errors` attribute of the result table): '5:38:03.1143 -16:32:42.5069': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2656 raised an error (recorded in the `errors` attribute of the result table): '5:59:13.1106 -16:44:57.859': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2669 raised an error (recorded in the `errors` attribute of the result table): '5:52:29.1415 -16:44:48.9074': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2680 raised an error (recorded in the `errors` attribute of the result table): '5:25:50.6722 -16:24:56.7412': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2685 raised an error (recorded in the `errors` attribute of the result table): '5:20:03.4602 -16:20:06.5395': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2693 raised an error (recorded in the `errors` attribute of the result table): '5:26:29.4969 -16:26:18.481': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2701 raised an error (recorded in the `errors` attribute of the result table): '5:49:41.1602 -16:46:40.2128': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2705 raised an error (recorded in the `errors` attribute of the result table): '5:58:20.1099 -16:56:39.0476': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2713 raised an error (recorded in the `errors` attribute of the result table): '5:41:24.3877 -16:47:09.5772': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2720 raised an error (recorded in the `errors` attribute of the result table): '5:48:32.4783 -16:53:46.992': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2725 raised an error (recorded in the `errors` attribute of the result table): '5:19:30.152 -16:27:24.1937': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2734 raised an error (recorded in the `errors` attribute of the result table): '6:05:07.9764 -16:59:18.43': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2743 raised an error (recorded in the `errors` attribute of the result table): '5:57:58.5224 -17:03:07.8762': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2758 raised an error (recorded in the `errors` attribute of the result table): '5:33:34.1484 -16:42:53.5132': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2783 raised an error (recorded in the `errors` attribute of the result table): '5:44:21.9598 -16:58:00.3572': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2788 raised an error (recorded in the `errors` attribute of the result table): '5:58:31.1547 -17:09:21.8311': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2798 raised an error (recorded in the `errors` attribute of the result table): '5:46:07.7664 -17:01:27.4328': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2801 raised an error (recorded in the `errors` attribute of the result table): '5:20:01.8887 -16:41:23.7371': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2807 raised an error (recorded in the `errors` attribute of the result table): '5:37:17.7725 -16:46:55.2371': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2813 raised an error (recorded in the `errors` attribute of the result table): '6:02:21.2872 -17:15:29.2114': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2825 raised an error (recorded in the `errors` attribute of the result table): '6:01:28.0131 -17:50:10.3165': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2836 raised an error (recorded in the `errors` attribute of the result table): '5:29:38.5774 -17:29:41.868': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2846 raised an error (recorded in the `errors` attribute of the result table): '5:49:41.1132 -17:21:30.148': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2891 raised an error (recorded in the `errors` attribute of the result table): '5:39:43.9978 -17:28:43.58': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2896 raised an error (recorded in the `errors` attribute of the result table): '5:38:19.5307 -17:06:03.9083': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2906 raised an error (recorded in the `errors` attribute of the result table): '5:27:55.7025 -17:01:17.7597': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2932 raised an error (recorded in the `errors` attribute of the result table): '5:27:54.8834 -16:58:52.5041': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2943 raised an error (recorded in the `errors` attribute of the result table): '6:05:05.7688 -17:35:40.6027': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2953 raised an error (recorded in the `errors` attribute of the result table): '5:44:50.4263 -17:49:39.8749': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2959 raised an error (recorded in the `errors` attribute of the result table): '5:25:07.1941 -17:09:55.1325': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2964 raised an error (recorded in the `errors` attribute of the result table): '5:44:23.6072 -17:41:25.8852': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2968 raised an error (recorded in the `errors` attribute of the result table): '5:27:25.4463 -17:12:50.1192': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2982 raised an error (recorded in the `errors` attribute of the result table): '5:57:44.2566 -17:39:36.5671': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2988 raised an error (recorded in the `errors` attribute of the result table): '5:53:33.3921 -17:41:41.1879': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2990 raised an error (recorded in the `errors` attribute of the result table): '5:50:10.8739 -17:37:55.1837': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 2996 raised an error (recorded in the `errors` attribute of the result table): '5:24:09.2921 -16:49:57.2642': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3000 raised an error (recorded in the `errors` attribute of the result table): '5:58:32.9906 -17:47:28.9851': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3013 raised an error (recorded in the `errors` attribute of the result table): '5:54:19.7443 -17:23:18.6633': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3021 raised an error (recorded in the `errors` attribute of the result table): '6:00:38.7154 -17:24:56.1814': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3025 raised an error (recorded in the `errors` attribute of the result table): '5:39:06.1108 -17:25:18.7349': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3036 raised an error (recorded in the `errors` attribute of the result table): '5:59:44.2704 -17:31:54.5374': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3041 raised an error (recorded in the `errors` attribute of the result table): '5:50:56.0586 -17:43:19.4852': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3060 raised an error (recorded in the `errors` attribute of the result table): '5:51:29.5297 -17:29:25.4088': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3066 raised an error (recorded in the `errors` attribute of the result table): '5:25:47.9396 -17:08:57.7206': No astronomical object found :  \n",
      "  (error.line, error.msg))\n",
      "/usr/local/lib/python3.6/dist-packages/astroquery/simbad/core.py:138: UserWarning: Warning: The script line number 3071 raised an error (recorded in the `errors` attribute of the result table): '5:43:28.2921 -17:40:27.0828': No astronomical object found :\n",
      "  (error.line, error.msg))\n"
     ]
    }
   ],
   "source": [
    "result_table = Simbad.query_region(orig_coord,\n",
    "                                   radius=search_radius)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[SimbadError(line=3, msg=\"'5:54:46.6185 -6:28:39.4625': No astronomical object found :  \"),\n",
       " SimbadError(line=6, msg=\"'6:00:43.2001 -6:30:46.0154': No astronomical object found :  \"),\n",
       " SimbadError(line=9, msg=\"'5:46:19.8309 -6:25:53.8313': No astronomical object found :  \"),\n",
       " SimbadError(line=12, msg=\"'6:03:46.09 -6:31:44.0361': No astronomical object found :  \"),\n",
       " SimbadError(line=15, msg=\"'5:44:24.0825 -6:25:19.1065': No astronomical object found :  \"),\n",
       " SimbadError(line=23, msg=\"'5:44:42.9476 -6:25:26.0638': No astronomical object found :  \"),\n",
       " SimbadError(line=32, msg=\"'6:00:22.2388 -6:33:23.872': No astronomical object found :  \"),\n",
       " SimbadError(line=45, msg=\"'5:41:18.6673 -6:30:07.2495': No astronomical object found :  \"),\n",
       " SimbadError(line=55, msg=\"'5:41:19.3054 -6:32:59.9194': No astronomical object found :  \"),\n",
       " SimbadError(line=65, msg=\"'5:40:55.6155 -6:38:47.3044': No astronomical object found :  \"),\n",
       " SimbadError(line=73, msg=\"'5:46:12.6611 -6:42:57.5814': No astronomical object found :  \"),\n",
       " SimbadError(line=87, msg=\"'6:07:08.4333 -6:55:03.2392': No astronomical object found :  \"),\n",
       " SimbadError(line=93, msg=\"'5:46:03.708 -6:48:18.5233': No astronomical object found :  \"),\n",
       " SimbadError(line=99, msg=\"'6:05:47.5077 -6:53:34.6957': No astronomical object found :  \"),\n",
       " SimbadError(line=103, msg=\"'6:01:34.973 -6:49:00.8083': No astronomical object found :  \"),\n",
       " SimbadError(line=108, msg=\"'6:02:16.9475 -6:51:08.7275': No astronomical object found :  \"),\n",
       " SimbadError(line=119, msg=\"'6:04:33.5953 -6:57:14.2722': No astronomical object found :  \"),\n",
       " SimbadError(line=132, msg=\"'5:48:22.2628 -6:59:04.8152': No astronomical object found :  \"),\n",
       " SimbadError(line=148, msg=\"'5:41:38.0422 -6:51:24.2334': No astronomical object found :  \"),\n",
       " SimbadError(line=157, msg=\"'6:04:54.9376 -7:03:12.8796': No astronomical object found :  \"),\n",
       " SimbadError(line=163, msg=\"'5:40:01.3065 -6:57:11.7548': No astronomical object found :  \"),\n",
       " SimbadError(line=167, msg=\"'6:05:59.5807 -7:01:23.0425': No astronomical object found :  \"),\n",
       " SimbadError(line=174, msg=\"'5:32:53.2078 -7:02:59.9611': No astronomical object found :  \"),\n",
       " SimbadError(line=182, msg=\"'5:57:49.3457 -6:48:49.8949': No astronomical object found :  \"),\n",
       " SimbadError(line=185, msg=\"'5:58:22.1465 -7:03:49.772': No astronomical object found :  \"),\n",
       " SimbadError(line=188, msg=\"'5:44:06.7162 -7:09:01.5432': No astronomical object found :  \"),\n",
       " SimbadError(line=198, msg=\"'5:43:36.3152 -7:10:07.0705': No astronomical object found :  \"),\n",
       " SimbadError(line=203, msg=\"'5:55:29.4151 -6:47:09.457': No astronomical object found :  \"),\n",
       " SimbadError(line=211, msg=\"'5:31:23.6858 -7:09:27.3845': No astronomical object found :  \"),\n",
       " SimbadError(line=219, msg=\"'6:07:06.7503 -7:25:31.8716': No astronomical object found :  \"),\n",
       " SimbadError(line=235, msg=\"'5:50:52.2192 -7:23:19.6157': No astronomical object found :  \"),\n",
       " SimbadError(line=247, msg=\"'6:04:34.6992 -7:30:45.2409': No astronomical object found :  \"),\n",
       " SimbadError(line=251, msg=\"'5:46:12.1647 -7:19:05.0352': No astronomical object found :  \"),\n",
       " SimbadError(line=255, msg=\"'5:45:46.2329 -7:25:43.3861': No astronomical object found :  \"),\n",
       " SimbadError(line=259, msg=\"'5:46:18.8278 -7:23:51.1373': No astronomical object found :  \"),\n",
       " SimbadError(line=263, msg=\"'6:03:44.3869 -7:33:13.604': No astronomical object found :  \"),\n",
       " SimbadError(line=285, msg=\"'5:32:25.9788 -7:26:44.8969': No astronomical object found :  \"),\n",
       " SimbadError(line=288, msg=\"'6:02:35.9626 -7:34:35.6695': No astronomical object found :  \"),\n",
       " SimbadError(line=293, msg=\"'6:05:05.9639 -7:37:18.2763': No astronomical object found :  \"),\n",
       " SimbadError(line=302, msg=\"'5:55:01.914 -7:35:40.9923': No astronomical object found :  \"),\n",
       " SimbadError(line=305, msg=\"'5:48:43.0629 -7:28:02.7062': No astronomical object found :  \"),\n",
       " SimbadError(line=313, msg=\"'5:31:59.9293 -7:24:25.5454': No astronomical object found :  \"),\n",
       " SimbadError(line=315, msg=\"'5:43:54.14 -7:33:27.4551': No astronomical object found :  \"),\n",
       " SimbadError(line=323, msg=\"'5:57:55.5832 -7:34:47.8306': No astronomical object found :  \"),\n",
       " SimbadError(line=330, msg=\"'5:31:07.7834 -7:31:37.5784': No astronomical object found :  \"),\n",
       " SimbadError(line=338, msg=\"'5:47:37.1533 -7:38:13.8004': No astronomical object found :  \"),\n",
       " SimbadError(line=354, msg=\"'5:29:23.0097 -7:35:50.4853': No astronomical object found :  \"),\n",
       " SimbadError(line=357, msg=\"'5:26:30.6418 -7:34:41.9677': No astronomical object found :  \"),\n",
       " SimbadError(line=360, msg=\"'6:05:22.7262 -7:53:05.9215': No astronomical object found :  \"),\n",
       " SimbadError(line=366, msg=\"'5:51:03.6421 -7:35:39.4492': No astronomical object found :  \"),\n",
       " SimbadError(line=372, msg=\"'6:05:46.2222 -7:49:02.1365': No astronomical object found :  \"),\n",
       " SimbadError(line=374, msg=\"'5:45:40.7488 -7:41:08.1906': No astronomical object found :  \"),\n",
       " SimbadError(line=379, msg=\"'5:59:59.8441 -7:55:37.6416': No astronomical object found :  \"),\n",
       " SimbadError(line=381, msg=\"'5:30:06.6286 -7:18:35.6607': No astronomical object found :  \"),\n",
       " SimbadError(line=385, msg=\"'6:04:03.6071 -7:56:43.232': No astronomical object found :  \"),\n",
       " SimbadError(line=392, msg=\"'6:00:55.4677 -7:58:45.1929': No astronomical object found :  \"),\n",
       " SimbadError(line=404, msg=\"'6:01:48.8443 -8:03:03.8549': No astronomical object found :  \"),\n",
       " SimbadError(line=414, msg=\"'5:32:41.7544 -7:51:28.5678': No astronomical object found :  \"),\n",
       " SimbadError(line=420, msg=\"'6:03:35.1878 -8:06:02.0825': No astronomical object found :  \"),\n",
       " SimbadError(line=423, msg=\"'5:57:49.1351 -8:05:35.21': No astronomical object found :  \"),\n",
       " SimbadError(line=427, msg=\"'6:03:44.2203 -8:04:22.2819': No astronomical object found :  \"),\n",
       " SimbadError(line=439, msg=\"'5:34:25.5409 -7:59:45.9488': No astronomical object found :  \"),\n",
       " SimbadError(line=444, msg=\"'5:37:27.8187 -8:00:49.8493': No astronomical object found :  \"),\n",
       " SimbadError(line=468, msg=\"'5:31:31.8753 -8:08:58.1762': No astronomical object found :  \"),\n",
       " SimbadError(line=473, msg=\"'5:52:09.7131 -8:15:09.356': No astronomical object found :  \"),\n",
       " SimbadError(line=480, msg=\"'5:57:59.4528 -8:21:54.1727': No astronomical object found :  \"),\n",
       " SimbadError(line=493, msg=\"'5:58:36.1121 -8:22:53.9066': No astronomical object found :  \"),\n",
       " SimbadError(line=501, msg=\"'5:50:17.0742 -8:23:36.5537': No astronomical object found :  \"),\n",
       " SimbadError(line=503, msg=\"'5:52:38.6509 -8:09:36.1061': No astronomical object found :  \"),\n",
       " SimbadError(line=510, msg=\"'5:51:17.6021 -8:26:18.4644': No astronomical object found :  \"),\n",
       " SimbadError(line=514, msg=\"'6:00:49.5903 -8:16:40.0262': No astronomical object found :  \"),\n",
       " SimbadError(line=516, msg=\"'6:03:46.8335 -8:32:07.2869': No astronomical object found :  \"),\n",
       " SimbadError(line=518, msg=\"'5:24:16.6469 -8:16:16.8974': No astronomical object found :  \"),\n",
       " SimbadError(line=525, msg=\"'5:29:18.8373 -8:20:25.1641': No astronomical object found :  \"),\n",
       " SimbadError(line=541, msg=\"'5:56:45.0774 -8:39:47.134': No astronomical object found :  \"),\n",
       " SimbadError(line=544, msg=\"'5:46:00.3742 -8:31:11.892': No astronomical object found :  \"),\n",
       " SimbadError(line=552, msg=\"'6:04:38.9091 -8:44:34.724': No astronomical object found :  \"),\n",
       " SimbadError(line=559, msg=\"'5:58:14.336 -8:44:12.0222': No astronomical object found :  \"),\n",
       " SimbadError(line=565, msg=\"'6:02:12.9171 -8:41:37.7323': No astronomical object found :  \"),\n",
       " SimbadError(line=572, msg=\"'5:52:32.2682 -8:44:59.8645': No astronomical object found :  \"),\n",
       " SimbadError(line=578, msg=\"'5:27:52.0167 -8:33:54.9608': No astronomical object found :  \"),\n",
       " SimbadError(line=583, msg=\"'5:47:49.7984 -8:40:59.2733': No astronomical object found :  \"),\n",
       " SimbadError(line=593, msg=\"'5:28:13.8045 -8:37:52.8216': No astronomical object found :  \"),\n",
       " SimbadError(line=597, msg=\"'5:28:03.674 -8:40:18.5428': No astronomical object found :  \"),\n",
       " SimbadError(line=605, msg=\"'5:51:25.6588 -8:52:09.0567': No astronomical object found :  \"),\n",
       " SimbadError(line=610, msg=\"'5:35:05.9998 -8:44:08.4317': No astronomical object found :  \"),\n",
       " SimbadError(line=618, msg=\"'5:56:04.9929 -8:56:43.1457': No astronomical object found :  \"),\n",
       " SimbadError(line=623, msg=\"'5:22:51.2162 -8:43:41.965': No astronomical object found :  \"),\n",
       " SimbadError(line=631, msg=\"'6:06:40.7675 -9:06:07.4004': No astronomical object found :  \"),\n",
       " SimbadError(line=637, msg=\"'5:24:00.0726 -8:39:55.811': No astronomical object found :  \"),\n",
       " SimbadError(line=650, msg=\"'6:06:58.3749 -9:07:22.1416': No astronomical object found :  \"),\n",
       " SimbadError(line=658, msg=\"'5:24:25.0088 -8:45:42.9524': No astronomical object found :  \"),\n",
       " SimbadError(line=663, msg=\"'5:37:52.2177 -8:58:03.4065': No astronomical object found :  \"),\n",
       " SimbadError(line=673, msg=\"'6:01:29.2563 -9:07:25.5798': No astronomical object found :  \"),\n",
       " SimbadError(line=685, msg=\"'5:47:10.2104 -9:08:27.3413': No astronomical object found :  \"),\n",
       " SimbadError(line=688, msg=\"'5:34:53.3733 -9:02:48.5651': No astronomical object found :  \"),\n",
       " SimbadError(line=694, msg=\"'6:01:21.434 -9:10:03.1232': No astronomical object found :  \"),\n",
       " SimbadError(line=698, msg=\"'5:37:11.3435 -9:06:55.1523': No astronomical object found :  \"),\n",
       " SimbadError(line=703, msg=\"'5:53:41.9848 -9:17:42.4057': No astronomical object found :  \"),\n",
       " SimbadError(line=708, msg=\"'5:30:28.5884 -9:05:02.4385': No astronomical object found :  \"),\n",
       " SimbadError(line=711, msg=\"'5:36:30.5052 -9:05:32.3889': No astronomical object found :  \"),\n",
       " SimbadError(line=715, msg=\"'5:52:57.9198 -9:16:37.3207': No astronomical object found :  \"),\n",
       " SimbadError(line=730, msg=\"'6:02:52.8541 -9:28:46.9649': No astronomical object found :  \"),\n",
       " SimbadError(line=738, msg=\"'5:50:01.8876 -9:23:27.6186': No astronomical object found :  \"),\n",
       " SimbadError(line=740, msg=\"'5:51:19.5216 -9:26:09.6465': No astronomical object found :  \"),\n",
       " SimbadError(line=742, msg=\"'5:38:05.674 -9:16:21.2629': No astronomical object found :  \"),\n",
       " SimbadError(line=752, msg=\"'5:35:56.0098 -9:21:13.2321': No astronomical object found :  \"),\n",
       " SimbadError(line=755, msg=\"'6:00:45.8942 -9:33:34.1958': No astronomical object found :  \"),\n",
       " SimbadError(line=761, msg=\"'5:25:06.4178 -9:13:18.2471': No astronomical object found :  \"),\n",
       " SimbadError(line=766, msg=\"'5:25:16.9126 -9:13:53.512': No astronomical object found :  \"),\n",
       " SimbadError(line=770, msg=\"'5:28:11.8192 -9:19:28.0712': No astronomical object found :  \"),\n",
       " SimbadError(line=779, msg=\"'5:47:49.0469 -9:29:13.6592': No astronomical object found :  \"),\n",
       " SimbadError(line=781, msg=\"'5:38:25.0442 -9:14:39.5031': No astronomical object found :  \"),\n",
       " SimbadError(line=791, msg=\"'5:56:01.7025 -9:39:10.0786': No astronomical object found :  \"),\n",
       " SimbadError(line=794, msg=\"'5:47:48.1706 -9:27:28.6333': No astronomical object found :  \"),\n",
       " SimbadError(line=799, msg=\"'5:55:46.0747 -9:43:46.8366': No astronomical object found :  \"),\n",
       " SimbadError(line=802, msg=\"'5:56:36.4287 -9:40:20.4618': No astronomical object found :  \"),\n",
       " SimbadError(line=806, msg=\"'5:28:44.7065 -9:29:56.3946': No astronomical object found :  \"),\n",
       " SimbadError(line=814, msg=\"'5:37:34.9921 -9:34:08.0259': No astronomical object found :  \"),\n",
       " SimbadError(line=820, msg=\"'5:43:53.3434 -9:28:28.5713': No astronomical object found :  \"),\n",
       " SimbadError(line=825, msg=\"'5:54:02.6077 -9:46:49.4173': No astronomical object found :  \"),\n",
       " SimbadError(line=828, msg=\"'6:07:30.6358 -9:46:58.9726': No astronomical object found :  \"),\n",
       " SimbadError(line=834, msg=\"'6:01:49.6607 -9:46:23.9903': No astronomical object found :  \"),\n",
       " SimbadError(line=838, msg=\"'5:59:01.1278 -9:44:10.3107': No astronomical object found :  \"),\n",
       " SimbadError(line=842, msg=\"'6:05:36.5501 -9:44:30.4541': No astronomical object found :  \"),\n",
       " SimbadError(line=847, msg=\"'5:26:55.9108 -9:34:06.6331': No astronomical object found :  \"),\n",
       " SimbadError(line=854, msg=\"'5:34:59.2385 -9:40:07.9531': No astronomical object found :  \"),\n",
       " SimbadError(line=857, msg=\"'5:54:01.957 -9:51:06.8988': No astronomical object found :  \"),\n",
       " SimbadError(line=874, msg=\"'5:45:33.5441 -9:52:24.072': No astronomical object found :  \"),\n",
       " SimbadError(line=881, msg=\"'5:46:06.6171 -9:54:01.9199': No astronomical object found :  \"),\n",
       " SimbadError(line=887, msg=\"'5:51:37.8837 -9:50:51.1859': No astronomical object found :  \"),\n",
       " SimbadError(line=895, msg=\"'5:21:25.7167 -9:46:28.0244': No astronomical object found :  \"),\n",
       " SimbadError(line=900, msg=\"'5:49:59.6803 -9:54:19.362': No astronomical object found :  \"),\n",
       " SimbadError(line=906, msg=\"'5:49:55.1768 -9:59:12.0007': No astronomical object found :  \"),\n",
       " SimbadError(line=913, msg=\"'6:06:10.6453 -10:06:27.1448': No astronomical object found :  \"),\n",
       " SimbadError(line=920, msg=\"'5:21:29.3633 -9:39:37.3439': No astronomical object found :  \"),\n",
       " SimbadError(line=928, msg=\"'5:40:26.4392 -10:00:29.6073': No astronomical object found :  \"),\n",
       " SimbadError(line=935, msg=\"'5:48:20.9278 -10:05:54.7594': No astronomical object found :  \"),\n",
       " SimbadError(line=939, msg=\"'6:03:27.472 -10:09:49.2621': No astronomical object found :  \"),\n",
       " SimbadError(line=944, msg=\"'5:34:09.6733 -9:59:34.7145': No astronomical object found :  \"),\n",
       " SimbadError(line=957, msg=\"'6:00:38.8029 -10:16:32.2714': No astronomical object found :  \"),\n",
       " SimbadError(line=961, msg=\"'6:01:37.7956 -10:09:19.2177': No astronomical object found :  \"),\n",
       " SimbadError(line=965, msg=\"'5:58:50.108 -10:10:01.1538': No astronomical object found :  \"),\n",
       " SimbadError(line=968, msg=\"'5:51:56.7625 -10:09:29.783': No astronomical object found :  \"),\n",
       " SimbadError(line=971, msg=\"'5:43:54.3848 -10:11:04.5784': No astronomical object found :  \"),\n",
       " SimbadError(line=981, msg=\"'5:37:19.7584 -10:07:38.6717': No astronomical object found :  \"),\n",
       " SimbadError(line=986, msg=\"'5:44:51.1542 -10:14:20.5122': No astronomical object found :  \"),\n",
       " SimbadError(line=990, msg=\"'5:58:56.6341 -10:16:18.4375': No astronomical object found :  \"),\n",
       " SimbadError(line=994, msg=\"'5:59:41.5971 -10:21:02.7389': No astronomical object found :  \"),\n",
       " SimbadError(line=996, msg=\"'5:35:48.9947 -10:11:09.0201': No astronomical object found :  \"),\n",
       " SimbadError(line=998, msg=\"'5:57:46.369 -10:17:26.3461': No astronomical object found :  \"),\n",
       " SimbadError(line=1003, msg=\"'6:02:44.5017 -10:16:04.5383': No astronomical object found :  \"),\n",
       " SimbadError(line=1013, msg=\"'5:31:31.9378 -10:09:13.4706': No astronomical object found :  \"),\n",
       " SimbadError(line=1020, msg=\"'6:03:30.5401 -10:26:40.8129': No astronomical object found :  \"),\n",
       " SimbadError(line=1023, msg=\"'5:42:00.0561 -10:18:39.7155': No astronomical object found :  \"),\n",
       " SimbadError(line=1027, msg=\"'5:44:13.9341 -10:20:24.9753': No astronomical object found :  \"),\n",
       " SimbadError(line=1029, msg=\"'6:00:51.3898 -10:28:15.037': No astronomical object found :  \"),\n",
       " SimbadError(line=1034, msg=\"'6:05:00.9803 -10:28:17.0472': No astronomical object found :  \"),\n",
       " SimbadError(line=1038, msg=\"'6:06:12.1692 -10:28:49.6203': No astronomical object found :  \"),\n",
       " SimbadError(line=1042, msg=\"'5:25:45.4878 -10:07:25.5397': No astronomical object found :  \"),\n",
       " SimbadError(line=1046, msg=\"'5:29:38.5767 -10:15:16.9531': No astronomical object found :  \"),\n",
       " SimbadError(line=1049, msg=\"'5:59:54.5383 -10:28:50.5337': No astronomical object found :  \"),\n",
       " SimbadError(line=1052, msg=\"'5:28:29.5906 -10:15:57.0752': No astronomical object found :  \"),\n",
       " SimbadError(line=1054, msg=\"'5:31:00.0281 -10:15:42.0941': No astronomical object found :  \"),\n",
       " SimbadError(line=1057, msg=\"'6:05:25.9091 -10:34:02.7258': No astronomical object found :  \"),\n",
       " SimbadError(line=1064, msg=\"'5:30:04.0167 -10:21:26.8709': No astronomical object found :  \"),\n",
       " SimbadError(line=1071, msg=\"'5:49:47.3832 -10:34:41.4704': No astronomical object found :  \"),\n",
       " SimbadError(line=1075, msg=\"'5:50:23.8947 -10:35:29.5459': No astronomical object found :  \"),\n",
       " SimbadError(line=1079, msg=\"'5:56:40.1311 -10:32:52.7114': No astronomical object found :  \"),\n",
       " SimbadError(line=1084, msg=\"'5:37:06.3276 -10:32:05.566': No astronomical object found :  \"),\n",
       " SimbadError(line=1086, msg=\"'6:07:15.4342 -10:41:01.1': No astronomical object found :  \"),\n",
       " SimbadError(line=1090, msg=\"'5:56:51.2754 -10:39:34.8636': No astronomical object found :  \"),\n",
       " SimbadError(line=1093, msg=\"'5:38:37.8236 -10:34:35.9214': No astronomical object found :  \"),\n",
       " SimbadError(line=1096, msg=\"'6:04:28.8998 -10:49:16.9583': No astronomical object found :  \"),\n",
       " SimbadError(line=1099, msg=\"'5:22:02.6074 -10:20:33.5777': No astronomical object found :  \"),\n",
       " SimbadError(line=1108, msg=\"'5:56:17.4881 -10:51:48.1564': No astronomical object found :  \"),\n",
       " SimbadError(line=1112, msg=\"'5:47:57.945 -10:45:25.9642': No astronomical object found :  \"),\n",
       " SimbadError(line=1114, msg=\"'5:47:42.8781 -9:51:59.13': No astronomical object found :  \"),\n",
       " SimbadError(line=1118, msg=\"'6:03:02.0754 -10:50:54.4284': No astronomical object found :  \"),\n",
       " SimbadError(line=1126, msg=\"'5:40:46.541 -10:40:25.474': No astronomical object found :  \"),\n",
       " SimbadError(line=1130, msg=\"'5:48:33.9123 -10:50:21.1677': No astronomical object found :  \"),\n",
       " SimbadError(line=1134, msg=\"'5:59:26.9922 -10:49:00.1195': No astronomical object found :  \"),\n",
       " SimbadError(line=1136, msg=\"'5:44:03.3229 -10:48:23.797': No astronomical object found :  \"),\n",
       " SimbadError(line=1140, msg=\"'5:33:12.4262 -10:40:44.0184': No astronomical object found :  \"),\n",
       " SimbadError(line=1144, msg=\"'5:59:22.5182 -10:56:16.7286': No astronomical object found :  \"),\n",
       " SimbadError(line=1146, msg=\"'5:55:55.5649 -10:58:50.0298': No astronomical object found :  \"),\n",
       " SimbadError(line=1154, msg=\"'5:32:48.9869 -10:45:27.9926': No astronomical object found :  \"),\n",
       " SimbadError(line=1158, msg=\"'5:59:04.3899 -11:00:51.3037': No astronomical object found :  \"),\n",
       " SimbadError(line=1163, msg=\"'5:46:09.0737 -10:56:22.3786': No astronomical object found :  \"),\n",
       " SimbadError(line=1166, msg=\"'5:29:16.7607 -10:49:40.0347': No astronomical object found :  \"),\n",
       " SimbadError(line=1171, msg=\"'5:22:17.5528 -10:42:26.3406': No astronomical object found :  \"),\n",
       " SimbadError(line=1178, msg=\"'5:52:20.3642 -11:04:11.2447': No astronomical object found :  \"),\n",
       " SimbadError(line=1185, msg=\"'5:59:41.3803 -11:09:07.6472': No astronomical object found :  \"),\n",
       " SimbadError(line=1193, msg=\"'5:52:15.8362 -11:10:45.6122': No astronomical object found :  \"),\n",
       " SimbadError(line=1196, msg=\"'5:38:02.0124 -11:02:34.989': No astronomical object found :  \"),\n",
       " SimbadError(line=1205, msg=\"'5:47:51.1853 -11:09:16.3636': No astronomical object found :  \"),\n",
       " SimbadError(line=1212, msg=\"'6:04:51.9567 -11:15:26.6939': No astronomical object found :  \"),\n",
       " SimbadError(line=1217, msg=\"'5:42:00.5259 -11:04:10.9192': No astronomical object found :  \"),\n",
       " SimbadError(line=1219, msg=\"'5:51:54.0234 -11:08:20.9936': No astronomical object found :  \"),\n",
       " SimbadError(line=1224, msg=\"'5:51:33.0225 -11:13:47.6596': No astronomical object found :  \"),\n",
       " SimbadError(line=1234, msg=\"'5:44:18.0902 -11:11:52.2686': No astronomical object found :  \"),\n",
       " SimbadError(line=1236, msg=\"'5:50:53.8174 -11:12:06.6459': No astronomical object found :  \"),\n",
       " SimbadError(line=1240, msg=\"'5:27:38.6057 -11:02:58.7372': No astronomical object found :  \"),\n",
       " SimbadError(line=1246, msg=\"'5:53:03.3144 -11:14:17.5927': No astronomical object found :  \"),\n",
       " SimbadError(line=1256, msg=\"'5:42:34.6258 -11:13:53.5921': No astronomical object found :  \"),\n",
       " SimbadError(line=1262, msg=\"'5:47:09.5771 -11:17:51.4356': No astronomical object found :  \"),\n",
       " SimbadError(line=1273, msg=\"'5:59:32.5649 -11:25:24.7682': No astronomical object found :  \"),\n",
       " SimbadError(line=1283, msg=\"'6:01:31.2192 -11:24:59.5484': No astronomical object found :  \"),\n",
       " SimbadError(line=1290, msg=\"'5:58:52.3918 -11:28:43.4164': No astronomical object found :  \"),\n",
       " SimbadError(line=1292, msg=\"'5:48:50.0253 -11:25:19.541': No astronomical object found :  \"),\n",
       " SimbadError(line=1295, msg=\"'6:03:53.249 -11:32:26.8872': No astronomical object found :  \"),\n",
       " SimbadError(line=1299, msg=\"'5:50:51.6315 -11:31:12.243': No astronomical object found :  \"),\n",
       " SimbadError(line=1301, msg=\"'5:51:32.4461 -11:31:22.3709': No astronomical object found :  \"),\n",
       " SimbadError(line=1306, msg=\"'5:36:09.4889 -11:22:34.7733': No astronomical object found :  \"),\n",
       " SimbadError(line=1313, msg=\"'6:00:34.9636 -11:36:11.4814': No astronomical object found :  \"),\n",
       " SimbadError(line=1322, msg=\"'5:35:09.9859 -11:27:40.9748': No astronomical object found :  \"),\n",
       " SimbadError(line=1324, msg=\"'6:06:37.9402 -11:37:53.1302': No astronomical object found :  \"),\n",
       " SimbadError(line=1327, msg=\"'5:52:38.494 -11:37:35.7506': No astronomical object found :  \"),\n",
       " SimbadError(line=1332, msg=\"'5:33:12.4284 -11:27:53.845': No astronomical object found :  \"),\n",
       " SimbadError(line=1337, msg=\"'5:47:41.9406 -11:38:37.0505': No astronomical object found :  \"),\n",
       " SimbadError(line=1341, msg=\"'6:06:15.7665 -11:45:38.8334': No astronomical object found :  \"),\n",
       " SimbadError(line=1351, msg=\"'5:52:21.2707 -11:45:44.0349': No astronomical object found :  \"),\n",
       " SimbadError(line=1353, msg=\"'5:28:46.1873 -11:29:17.8951': No astronomical object found :  \"),\n",
       " SimbadError(line=1356, msg=\"'5:22:47.6726 -11:26:22.1294': No astronomical object found :  \"),\n",
       " SimbadError(line=1364, msg=\"'5:48:43.9957 -11:44:17.2307': No astronomical object found :  \"),\n",
       " SimbadError(line=1369, msg=\"'6:03:38.883 -11:50:43.5386': No astronomical object found :  \"),\n",
       " SimbadError(line=1376, msg=\"'5:45:41.4029 -11:48:37.2885': No astronomical object found :  \"),\n",
       " SimbadError(line=1380, msg=\"'6:02:58.7719 -11:57:06.2149': No astronomical object found :  \"),\n",
       " SimbadError(line=1392, msg=\"'5:27:53.6734 -11:38:23.7659': No astronomical object found :  \"),\n",
       " SimbadError(line=1395, msg=\"'5:27:23.3285 -11:45:39.9877': No astronomical object found :  \"),\n",
       " SimbadError(line=1410, msg=\"'6:04:35.8842 -12:07:50.0944': No astronomical object found :  \"),\n",
       " SimbadError(line=1419, msg=\"'6:06:16.3712 -12:11:44.211': No astronomical object found :  \"),\n",
       " SimbadError(line=1422, msg=\"'5:43:21.765 -12:02:22.3493': No astronomical object found :  \"),\n",
       " SimbadError(line=1428, msg=\"'5:54:03.1242 -12:07:47.8057': No astronomical object found :  \"),\n",
       " SimbadError(line=1431, msg=\"'5:40:49.2083 -12:07:34.3844': No astronomical object found :  \"),\n",
       " SimbadError(line=1443, msg=\"'5:30:02.5868 -12:01:58.1857': No astronomical object found :  \"),\n",
       " SimbadError(line=1449, msg=\"'5:57:57.4875 -11:32:37.8814': No astronomical object found :  \"),\n",
       " SimbadError(line=1456, msg=\"'5:55:57.4582 -12:02:19.7481': No astronomical object found :  \"),\n",
       " SimbadError(line=1462, msg=\"'5:53:31.543 -12:19:26.4582': No astronomical object found :  \"),\n",
       " SimbadError(line=1465, msg=\"'5:40:35.2588 -12:09:59.9842': No astronomical object found :  \"),\n",
       " SimbadError(line=1468, msg=\"'5:47:57.4543 -12:14:34.9119': No astronomical object found :  \"),\n",
       " SimbadError(line=1471, msg=\"'5:37:17.5627 -12:09:36.0082': No astronomical object found :  \"),\n",
       " SimbadError(line=1489, msg=\"'6:01:21.4196 -12:24:07.9932': No astronomical object found :  \"),\n",
       " SimbadError(line=1500, msg=\"'5:49:05.4114 -12:13:58.944': No astronomical object found :  \"),\n",
       " SimbadError(line=1511, msg=\"'5:59:27.0082 -12:30:46.6908': No astronomical object found :  \"),\n",
       " SimbadError(line=1515, msg=\"'5:59:01.0555 -12:31:45.5122': No astronomical object found :  \"),\n",
       " SimbadError(line=1523, msg=\"'5:31:17.363 -11:59:12.5083': No astronomical object found :  \"),\n",
       " SimbadError(line=1525, msg=\"'5:32:55.8142 -12:04:22.3345': No astronomical object found :  \"),\n",
       " SimbadError(line=1528, msg=\"'5:31:09.7831 -11:43:07.4501': No astronomical object found :  \"),\n",
       " SimbadError(line=1530, msg=\"'6:02:33.8842 -12:38:05.0404': No astronomical object found :  \"),\n",
       " SimbadError(line=1538, msg=\"'6:03:40.2701 -12:30:09.0346': No astronomical object found :  \"),\n",
       " SimbadError(line=1543, msg=\"'6:05:50.4235 -12:40:00.5496': No astronomical object found :  \"),\n",
       " SimbadError(line=1546, msg=\"'5:39:00.3296 -12:28:53.1322': No astronomical object found :  \"),\n",
       " SimbadError(line=1549, msg=\"'5:39:17.6251 -12:29:57.5544': No astronomical object found :  \"),\n",
       " SimbadError(line=1572, msg=\"'6:05:42.7854 -12:49:58.3297': No astronomical object found :  \"),\n",
       " SimbadError(line=1575, msg=\"'5:46:48.6357 -12:39:30.8201': No astronomical object found :  \"),\n",
       " SimbadError(line=1578, msg=\"'5:39:13.6299 -12:34:03.3789': No astronomical object found :  \"),\n",
       " SimbadError(line=1584, msg=\"'5:33:01.0867 -12:27:37.637': No astronomical object found :  \"),\n",
       " SimbadError(line=1586, msg=\"'6:04:36.1835 -12:49:08.5253': No astronomical object found :  \"),\n",
       " SimbadError(line=1592, msg=\"'5:52:49.0231 -12:37:36.3185': No astronomical object found :  \"),\n",
       " SimbadError(line=1600, msg=\"'5:58:14.9856 -12:50:49.4119': No astronomical object found :  \"),\n",
       " SimbadError(line=1608, msg=\"'5:58:36.8336 -12:50:22.2686': No astronomical object found :  \"),\n",
       " SimbadError(line=1612, msg=\"'5:35:02.9375 -12:40:10.4208': No astronomical object found :  \"),\n",
       " SimbadError(line=1616, msg=\"'6:04:36.6336 -12:54:49.7645': No astronomical object found :  \"),\n",
       " SimbadError(line=1626, msg=\"'5:48:51.1957 -12:51:30.6717': No astronomical object found :  \"),\n",
       " SimbadError(line=1631, msg=\"'5:32:51.716 -12:41:33.0182': No astronomical object found :  \"),\n",
       " SimbadError(line=1636, msg=\"'5:35:53.5204 -12:45:32.6241': No astronomical object found :  \"),\n",
       " SimbadError(line=1645, msg=\"'5:58:42.0951 -13:00:21.9401': No astronomical object found :  \"),\n",
       " SimbadError(line=1653, msg=\"'5:57:31.8168 -12:50:52.1723': No astronomical object found :  \"),\n",
       " SimbadError(line=1667, msg=\"'6:02:37.3164 -13:05:32.6312': No astronomical object found :  \"),\n",
       " SimbadError(line=1673, msg=\"'6:04:02.7171 -13:06:56.2124': No astronomical object found :  \"),\n",
       " SimbadError(line=1688, msg=\"'5:52:57.8397 -13:05:11.78': No astronomical object found :  \"),\n",
       " SimbadError(line=1693, msg=\"'5:39:46.0911 -12:50:13.8973': No astronomical object found :  \"),\n",
       " SimbadError(line=1701, msg=\"'6:02:34.8316 -13:13:58.7512': No astronomical object found :  \"),\n",
       " SimbadError(line=1709, msg=\"'5:58:21.2142 -13:12:25.4209': No astronomical object found :  \"),\n",
       " SimbadError(line=1713, msg=\"'5:30:02.8094 -12:53:37.9872': No astronomical object found :  \"),\n",
       " SimbadError(line=1716, msg=\"'5:51:16.3404 -12:53:42.2305': No astronomical object found :  \"),\n",
       " SimbadError(line=1721, msg=\"'5:53:40.9211 -13:08:01.9616': No astronomical object found :  \"),\n",
       " SimbadError(line=1734, msg=\"'6:01:17.0248 -13:20:55.7979': No astronomical object found :  \"),\n",
       " SimbadError(line=1741, msg=\"'5:58:57.0913 -13:23:26.382': No astronomical object found :  \"),\n",
       " SimbadError(line=1744, msg=\"'5:45:09.1751 -13:09:37.7403': No astronomical object found :  \"),\n",
       " SimbadError(line=1750, msg=\"'5:28:24.1953 -13:03:46.9855': No astronomical object found :  \"),\n",
       " SimbadError(line=1758, msg=\"'5:51:16.2338 -13:15:15.8514': No astronomical object found :  \"),\n",
       " SimbadError(line=1764, msg=\"'6:00:27.4447 -13:21:23.7478': No astronomical object found :  \"),\n",
       " SimbadError(line=1769, msg=\"'5:36:45.1219 -13:10:30.2938': No astronomical object found :  \"),\n",
       " SimbadError(line=1772, msg=\"'5:59:31.3189 -13:24:06.1087': No astronomical object found :  \"),\n",
       " SimbadError(line=1786, msg=\"'5:23:15.6793 -13:00:50.1795': No astronomical object found :  \"),\n",
       " SimbadError(line=1792, msg=\"'5:59:36.587 -13:30:09.5998': No astronomical object found :  \"),\n",
       " SimbadError(line=1795, msg=\"'6:02:43.5033 -13:30:41.4178': No astronomical object found :  \"),\n",
       " SimbadError(line=1814, msg=\"'6:02:48.8209 -13:34:38.9007': No astronomical object found :  \"),\n",
       " SimbadError(line=1821, msg=\"'5:58:36.2481 -13:36:20.0423': No astronomical object found :  \"),\n",
       " SimbadError(line=1824, msg=\"'5:43:12.8233 -13:26:31.6856': No astronomical object found :  \"),\n",
       " SimbadError(line=1833, msg=\"'5:58:13.4941 -13:35:47.009': No astronomical object found :  \"),\n",
       " SimbadError(line=1842, msg=\"'5:56:28.2821 -13:37:36.8131': No astronomical object found :  \"),\n",
       " SimbadError(line=1845, msg=\"'5:47:12.4814 -13:33:53.0635': No astronomical object found :  \"),\n",
       " SimbadError(line=1849, msg=\"'5:58:20.6227 -13:41:13.8309': No astronomical object found :  \"),\n",
       " SimbadError(line=1867, msg=\"'5:23:11.8668 -13:16:04.1944': No astronomical object found :  \"),\n",
       " SimbadError(line=1875, msg=\"'5:42:26.9469 -13:38:16.5155': No astronomical object found :  \"),\n",
       " SimbadError(line=1881, msg=\"'6:01:20.83 -13:49:25.3813': No astronomical object found :  \"),\n",
       " SimbadError(line=1885, msg=\"'5:47:59.4964 -13:46:27.2773': No astronomical object found :  \"),\n",
       " SimbadError(line=1898, msg=\"'5:44:12.4705 -13:46:17.7879': No astronomical object found :  \"),\n",
       " SimbadError(line=1905, msg=\"'5:45:27.8472 -13:49:44.0118': No astronomical object found :  \"),\n",
       " SimbadError(line=1909, msg=\"'5:47:23.2219 -13:50:58.2834': No astronomical object found :  \"),\n",
       " SimbadError(line=1915, msg=\"'6:02:04.6232 -13:57:54.9045': No astronomical object found :  \"),\n",
       " SimbadError(line=1924, msg=\"'5:56:53.0574 -13:56:34.744': No astronomical object found :  \"),\n",
       " SimbadError(line=1930, msg=\"'5:57:04.3657 -13:57:52.1817': No astronomical object found :  \"),\n",
       " SimbadError(line=1933, msg=\"'5:35:02.2356 -13:45:13.8418': No astronomical object found :  \"),\n",
       " SimbadError(line=1939, msg=\"'5:58:25.7683 -14:02:59.8977': No astronomical object found :  \"),\n",
       " SimbadError(line=1941, msg=\"'5:41:26.4503 -13:53:34.5302': No astronomical object found :  \"),\n",
       " SimbadError(line=1945, msg=\"'6:06:43.2875 -14:07:30.0118': No astronomical object found :  \"),\n",
       " SimbadError(line=1951, msg=\"'5:45:00.9076 -13:58:39.2815': No astronomical object found :  \"),\n",
       " SimbadError(line=1955, msg=\"'5:41:29.2576 -13:59:02.6253': No astronomical object found :  \"),\n",
       " SimbadError(line=1975, msg=\"'5:30:18.821 -13:36:13.1743': No astronomical object found :  \"),\n",
       " SimbadError(line=1981, msg=\"'6:03:44.8783 -14:16:55.9713': No astronomical object found :  \"),\n",
       " SimbadError(line=1995, msg=\"'5:37:21.5933 -14:02:00.6773': No astronomical object found :  \"),\n",
       " SimbadError(line=2000, msg=\"'5:36:33.3088 -14:04:01.3337': No astronomical object found :  \"),\n",
       " SimbadError(line=2019, msg=\"'5:58:49.5866 -14:26:56.0054': No astronomical object found :  \"),\n",
       " SimbadError(line=2023, msg=\"'6:00:13.5919 -14:25:44.7791': No astronomical object found :  \"),\n",
       " SimbadError(line=2031, msg=\"'6:04:40.0181 -14:31:36.9435': No astronomical object found :  \"),\n",
       " SimbadError(line=2037, msg=\"'6:05:04.8303 -14:33:51.1723': No astronomical object found :  \"),\n",
       " SimbadError(line=2040, msg=\"'5:38:30.146 -13:51:27.3176': No astronomical object found :  \"),\n",
       " SimbadError(line=2052, msg=\"'5:36:55.6527 -14:17:36.1402': No astronomical object found :  \"),\n",
       " SimbadError(line=2055, msg=\"'5:40:54.2649 -14:22:52.0318': No astronomical object found :  \"),\n",
       " SimbadError(line=2074, msg=\"'5:38:26.4287 -14:23:43.3761': No astronomical object found :  \"),\n",
       " SimbadError(line=2076, msg=\"'5:36:19.9487 -14:22:51.4259': No astronomical object found :  \"),\n",
       " SimbadError(line=2083, msg=\"'5:49:17.9338 -14:33:44.4131': No astronomical object found :  \"),\n",
       " SimbadError(line=2088, msg=\"'5:47:54.7627 -14:31:06.3449': No astronomical object found :  \"),\n",
       " SimbadError(line=2094, msg=\"'5:42:43.917 -14:32:30.8836': No astronomical object found :  \"),\n",
       " SimbadError(line=2109, msg=\"'5:59:01.367 -14:40:07.0515': No astronomical object found :  \"),\n",
       " SimbadError(line=2120, msg=\"'6:01:24.2032 -14:48:41.9362': No astronomical object found :  \"),\n",
       " SimbadError(line=2127, msg=\"'5:29:04.0816 -14:25:15.4746': No astronomical object found :  \"),\n",
       " SimbadError(line=2132, msg=\"'5:57:40.5452 -14:44:23.3547': No astronomical object found :  \"),\n",
       " SimbadError(line=2149, msg=\"'5:48:06.7942 -14:41:47.8065': No astronomical object found :  \"),\n",
       " SimbadError(line=2161, msg=\"'5:56:23.035 -14:15:50.4645': No astronomical object found :  \"),\n",
       " SimbadError(line=2166, msg=\"'5:41:46.7664 -14:41:46.7697': No astronomical object found :  \"),\n",
       " SimbadError(line=2173, msg=\"'5:29:42.1011 -14:34:29.9318': No astronomical object found :  \"),\n",
       " SimbadError(line=2176, msg=\"'6:04:34.4377 -14:57:05.6067': No astronomical object found :  \"),\n",
       " SimbadError(line=2180, msg=\"'6:03:02.1951 -14:49:31.4183': No astronomical object found :  \"),\n",
       " SimbadError(line=2182, msg=\"'5:58:25.6806 -14:58:06.8966': No astronomical object found :  \"),\n",
       " SimbadError(line=2184, msg=\"'6:02:31.7438 -15:00:26.7823': No astronomical object found :  \"),\n",
       " SimbadError(line=2193, msg=\"'5:57:44.9941 -14:58:43.0376': No astronomical object found :  \"),\n",
       " SimbadError(line=2208, msg=\"'6:02:08.3227 -15:04:51.0852': No astronomical object found :  \"),\n",
       " SimbadError(line=2213, msg=\"'6:03:05.4659 -15:01:41.6537': No astronomical object found :  \"),\n",
       " SimbadError(line=2217, msg=\"'5:22:20.2934 -14:39:04.8036': No astronomical object found :  \"),\n",
       " SimbadError(line=2220, msg=\"'6:00:20.6131 -15:05:04.0601': No astronomical object found :  \"),\n",
       " SimbadError(line=2226, msg=\"'6:03:53.9469 -15:09:26.3616': No astronomical object found :  \"),\n",
       " SimbadError(line=2237, msg=\"'6:05:42.1237 -15:09:04.5894': No astronomical object found :  \"),\n",
       " SimbadError(line=2245, msg=\"'5:56:16.7955 -15:10:43.9969': No astronomical object found :  \"),\n",
       " SimbadError(line=2247, msg=\"'5:46:02.4626 -15:04:06.3952': No astronomical object found :  \"),\n",
       " SimbadError(line=2256, msg=\"'6:05:16.7151 -15:17:20.1164': No astronomical object found :  \"),\n",
       " SimbadError(line=2262, msg=\"'5:34:38.9309 -15:01:06.2779': No astronomical object found :  \"),\n",
       " SimbadError(line=2274, msg=\"'5:28:56.6478 -15:01:32.4247': No astronomical object found :  \"),\n",
       " SimbadError(line=2280, msg=\"'6:01:46.2571 -15:23:55.4338': No astronomical object found :  \"),\n",
       " SimbadError(line=2287, msg=\"'5:28:15.9678 -15:03:44.1601': No astronomical object found :  \"),\n",
       " SimbadError(line=2292, msg=\"'5:38:14.9966 -15:12:32.6846': No astronomical object found :  \"),\n",
       " SimbadError(line=2301, msg=\"'5:38:54.4224 -15:17:27.6762': No astronomical object found :  \"),\n",
       " SimbadError(line=2313, msg=\"'5:25:37.6902 -15:05:22.4564': No astronomical object found :  \"),\n",
       " SimbadError(line=2315, msg=\"'5:51:00.541 -15:25:51.1774': No astronomical object found :  \"),\n",
       " SimbadError(line=2318, msg=\"'6:02:44.6112 -15:32:52.4318': No astronomical object found :  \"),\n",
       " SimbadError(line=2339, msg=\"'5:54:54.131 -15:37:41.2091': No astronomical object found :  \"),\n",
       " SimbadError(line=2352, msg=\"'6:01:59.07 -15:45:37.4305': No astronomical object found :  \"),\n",
       " SimbadError(line=2365, msg=\"'5:44:22.8052 -15:37:08.0625': No astronomical object found :  \"),\n",
       " SimbadError(line=2384, msg=\"'5:44:38.91 -15:42:16.9409': No astronomical object found :  \"),\n",
       " SimbadError(line=2398, msg=\"'6:02:15.8586 -15:50:31.3659': No astronomical object found :  \"),\n",
       " SimbadError(line=2402, msg=\"'6:02:34.8517 -15:55:15.3838': No astronomical object found :  \"),\n",
       " SimbadError(line=2407, msg=\"'5:58:22.6937 -15:47:57.7828': No astronomical object found :  \"),\n",
       " SimbadError(line=2413, msg=\"'5:38:30.8756 -15:41:11.569': No astronomical object found :  \"),\n",
       " SimbadError(line=2421, msg=\"'5:53:15.1843 -15:54:16.9806': No astronomical object found :  \"),\n",
       " SimbadError(line=2425, msg=\"'5:44:42.7273 -15:49:45.9831': No astronomical object found :  \"),\n",
       " SimbadError(line=2432, msg=\"'6:01:20.9786 -15:46:53.8296': No astronomical object found :  \"),\n",
       " SimbadError(line=2438, msg=\"'5:38:59.6123 -15:40:53.385': No astronomical object found :  \"),\n",
       " SimbadError(line=2450, msg=\"'6:02:53.4048 -15:58:28.6456': No astronomical object found :  \"),\n",
       " SimbadError(line=2453, msg=\"'5:50:44.5101 -15:55:12.3485': No astronomical object found :  \"),\n",
       " SimbadError(line=2465, msg=\"'6:01:43.639 -16:08:17.4989': No astronomical object found :  \"),\n",
       " SimbadError(line=2471, msg=\"'5:27:49.5091 -15:43:10.7256': No astronomical object found :  \"),\n",
       " SimbadError(line=2474, msg=\"'5:27:07.502 -15:39:31.5702': No astronomical object found :  \"),\n",
       " SimbadError(line=2491, msg=\"'5:21:10.8081 -15:38:40.5108': No astronomical object found :  \"),\n",
       " SimbadError(line=2500, msg=\"'5:45:22.7356 -16:05:20.518': No astronomical object found :  \"),\n",
       " SimbadError(line=2510, msg=\"'5:48:49.6892 -15:53:15.7208': No astronomical object found :  \"),\n",
       " SimbadError(line=2524, msg=\"'5:55:16.3293 -16:14:50.7978': No astronomical object found :  \"),\n",
       " SimbadError(line=2528, msg=\"'5:43:55.9988 -16:09:54.0997': No astronomical object found :  \"),\n",
       " SimbadError(line=2535, msg=\"'6:02:05.7237 -16:16:14.7083': No astronomical object found :  \"),\n",
       " SimbadError(line=2545, msg=\"'6:04:37.4711 -16:19:13.2679': No astronomical object found :  \"),\n",
       " SimbadError(line=2550, msg=\"'6:01:58.447 -16:22:22.9964': No astronomical object found :  \"),\n",
       " SimbadError(line=2558, msg=\"'5:34:47.8916 -16:02:39.1908': No astronomical object found :  \"),\n",
       " SimbadError(line=2566, msg=\"'6:03:47.8026 -16:18:49.0863': No astronomical object found :  \"),\n",
       " SimbadError(line=2568, msg=\"'5:40:21.0398 -16:11:14.2048': No astronomical object found :  \"),\n",
       " SimbadError(line=2576, msg=\"'5:56:16.1626 -16:20:16.3474': No astronomical object found :  \"),\n",
       " SimbadError(line=2579, msg=\"'5:52:48.2593 -16:13:20.2533': No astronomical object found :  \"),\n",
       " SimbadError(line=2583, msg=\"'5:52:02.0975 -16:21:33.4352': No astronomical object found :  \"),\n",
       " SimbadError(line=2586, msg=\"'5:51:48.4925 -16:23:33.3662': No astronomical object found :  \"),\n",
       " SimbadError(line=2590, msg=\"'5:54:48.9671 -16:25:17.377': No astronomical object found :  \"),\n",
       " SimbadError(line=2607, msg=\"'6:03:36.2319 -16:32:45.0899': No astronomical object found :  \"),\n",
       " SimbadError(line=2611, msg=\"'5:34:46.997 -16:14:43.2781': No astronomical object found :  \"),\n",
       " SimbadError(line=2620, msg=\"'5:27:30.8109 -16:12:29.8551': No astronomical object found :  \"),\n",
       " SimbadError(line=2630, msg=\"'5:50:33.6703 -16:23:23.7406': No astronomical object found :  \"),\n",
       " SimbadError(line=2634, msg=\"'5:45:58.7901 -16:28:22.4686': No astronomical object found :  \"),\n",
       " SimbadError(line=2641, msg=\"'5:20:25.0435 -16:11:38.7575': No astronomical object found :  \"),\n",
       " SimbadError(line=2643, msg=\"'5:57:07.2718 -16:41:53.4466': No astronomical object found :  \"),\n",
       " SimbadError(line=2646, msg=\"'6:02:56.0863 -16:39:46.5148': No astronomical object found :  \"),\n",
       " SimbadError(line=2654, msg=\"'5:38:03.1143 -16:32:42.5069': No astronomical object found :  \"),\n",
       " SimbadError(line=2656, msg=\"'5:59:13.1106 -16:44:57.859': No astronomical object found :  \"),\n",
       " SimbadError(line=2669, msg=\"'5:52:29.1415 -16:44:48.9074': No astronomical object found :  \"),\n",
       " SimbadError(line=2680, msg=\"'5:25:50.6722 -16:24:56.7412': No astronomical object found :  \"),\n",
       " SimbadError(line=2685, msg=\"'5:20:03.4602 -16:20:06.5395': No astronomical object found :  \"),\n",
       " SimbadError(line=2693, msg=\"'5:26:29.4969 -16:26:18.481': No astronomical object found :  \"),\n",
       " SimbadError(line=2701, msg=\"'5:49:41.1602 -16:46:40.2128': No astronomical object found :  \"),\n",
       " SimbadError(line=2705, msg=\"'5:58:20.1099 -16:56:39.0476': No astronomical object found :  \"),\n",
       " SimbadError(line=2713, msg=\"'5:41:24.3877 -16:47:09.5772': No astronomical object found :  \"),\n",
       " SimbadError(line=2720, msg=\"'5:48:32.4783 -16:53:46.992': No astronomical object found :  \"),\n",
       " SimbadError(line=2725, msg=\"'5:19:30.152 -16:27:24.1937': No astronomical object found :  \"),\n",
       " SimbadError(line=2734, msg=\"'6:05:07.9764 -16:59:18.43': No astronomical object found :  \"),\n",
       " SimbadError(line=2743, msg=\"'5:57:58.5224 -17:03:07.8762': No astronomical object found :  \"),\n",
       " SimbadError(line=2758, msg=\"'5:33:34.1484 -16:42:53.5132': No astronomical object found :  \"),\n",
       " SimbadError(line=2783, msg=\"'5:44:21.9598 -16:58:00.3572': No astronomical object found :  \"),\n",
       " SimbadError(line=2788, msg=\"'5:58:31.1547 -17:09:21.8311': No astronomical object found :  \"),\n",
       " SimbadError(line=2798, msg=\"'5:46:07.7664 -17:01:27.4328': No astronomical object found :  \"),\n",
       " SimbadError(line=2801, msg=\"'5:20:01.8887 -16:41:23.7371': No astronomical object found :  \"),\n",
       " SimbadError(line=2807, msg=\"'5:37:17.7725 -16:46:55.2371': No astronomical object found :  \"),\n",
       " SimbadError(line=2813, msg=\"'6:02:21.2872 -17:15:29.2114': No astronomical object found :  \"),\n",
       " SimbadError(line=2825, msg=\"'6:01:28.0131 -17:50:10.3165': No astronomical object found :  \"),\n",
       " SimbadError(line=2836, msg=\"'5:29:38.5774 -17:29:41.868': No astronomical object found :  \"),\n",
       " SimbadError(line=2846, msg=\"'5:49:41.1132 -17:21:30.148': No astronomical object found :  \"),\n",
       " SimbadError(line=2891, msg=\"'5:39:43.9978 -17:28:43.58': No astronomical object found :  \"),\n",
       " SimbadError(line=2896, msg=\"'5:38:19.5307 -17:06:03.9083': No astronomical object found :  \"),\n",
       " SimbadError(line=2906, msg=\"'5:27:55.7025 -17:01:17.7597': No astronomical object found :  \"),\n",
       " SimbadError(line=2932, msg=\"'5:27:54.8834 -16:58:52.5041': No astronomical object found :  \"),\n",
       " SimbadError(line=2943, msg=\"'6:05:05.7688 -17:35:40.6027': No astronomical object found :  \"),\n",
       " SimbadError(line=2953, msg=\"'5:44:50.4263 -17:49:39.8749': No astronomical object found :  \"),\n",
       " SimbadError(line=2959, msg=\"'5:25:07.1941 -17:09:55.1325': No astronomical object found :  \"),\n",
       " SimbadError(line=2964, msg=\"'5:44:23.6072 -17:41:25.8852': No astronomical object found :  \"),\n",
       " SimbadError(line=2968, msg=\"'5:27:25.4463 -17:12:50.1192': No astronomical object found :  \"),\n",
       " SimbadError(line=2982, msg=\"'5:57:44.2566 -17:39:36.5671': No astronomical object found :  \"),\n",
       " SimbadError(line=2988, msg=\"'5:53:33.3921 -17:41:41.1879': No astronomical object found :  \"),\n",
       " SimbadError(line=2990, msg=\"'5:50:10.8739 -17:37:55.1837': No astronomical object found :  \"),\n",
       " SimbadError(line=2996, msg=\"'5:24:09.2921 -16:49:57.2642': No astronomical object found :  \"),\n",
       " SimbadError(line=3000, msg=\"'5:58:32.9906 -17:47:28.9851': No astronomical object found :  \"),\n",
       " SimbadError(line=3013, msg=\"'5:54:19.7443 -17:23:18.6633': No astronomical object found :  \"),\n",
       " SimbadError(line=3021, msg=\"'6:00:38.7154 -17:24:56.1814': No astronomical object found :  \"),\n",
       " SimbadError(line=3025, msg=\"'5:39:06.1108 -17:25:18.7349': No astronomical object found :  \"),\n",
       " SimbadError(line=3036, msg=\"'5:59:44.2704 -17:31:54.5374': No astronomical object found :  \"),\n",
       " SimbadError(line=3041, msg=\"'5:50:56.0586 -17:43:19.4852': No astronomical object found :  \"),\n",
       " SimbadError(line=3060, msg=\"'5:51:29.5297 -17:29:25.4088': No astronomical object found :  \"),\n",
       " SimbadError(line=3066, msg=\"'5:25:47.9396 -17:08:57.7206': No astronomical object found :  \"),\n",
       " SimbadError(line=3071, msg=\"'5:43:28.2921 -17:40:27.0828': No astronomical object found :\")]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "result_table.errors"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
